;; Scheme values live in the engine's GC heap. Equal-shaped Wasm definitions
;; are structurally equal, so atoms and text explicitly carry category tags.

;; ---- Object representations ----

(type $vector (array (mut eqref)))
(type $call (func (param eqref (ref $vector)) (result eqref)))
(type $closure (struct (field (ref $call)) (field (ref $vector))))
(type $cell (struct (field (mut eqref))))
(type $pair (struct (field (mut eqref)) (field (mut eqref))))
(type $integer (struct (field i64)))
(type $float (struct (field f64)))
(type $atom (struct (field i32)))
(type $text (array (mut i32)))
(type $text_object (struct (field i32) (field (ref $text))))
(type $bytes (array (mut i8)))
(type $bytevector (struct (field (ref $bytes))))
(type $values (struct (field (ref $vector))))
(type $record_type (struct (field eqref) (field (ref $vector)) (field i32)))
(type $record (struct (field (ref $record_type)) (field (ref $vector))))
(type $extension (struct (field i32) (field i32)))
(global $false (ref $atom) (struct.new $atom (i32.const 0)))
(global $true (ref $atom) (struct.new $atom (i32.const 1)))
(global $nil (ref $atom) (struct.new $atom (i32.const 2)))
(global $unspecified (ref $atom) (struct.new $atom (i32.const 3)))
(global $eof (ref $atom) (struct.new $atom (i32.const 4)))
(global $uninitialized (ref $atom) (struct.new $atom (i32.const 5)))
(global $error_code (export "error_code") (mut i32) (i32.const 0))
(global $symbols (mut eqref) (ref.null eq))

;; ---- Calls and value counts ----

;; 1 number, 2 integer overflow, 3 range, 4 arity, 5 single value,
;; 6 uninitialized binding, 7 unsupported continuation, 8 type, 9 division by zero.
(func $fail (param $code i32)
  (global.set $error_code (local.get $code))
  (drop (call $rust_fail (local.get $code)))
  unreachable)
(func $defined (param $value eqref) (result eqref)
  (if (i32.or (ref.is_null (local.get $value))
              (ref.eq (local.get $value) (global.get $uninitialized)))
    (then (call $fail (i32.const 6))))
  (local.get $value))
(func $single (param $value eqref) (result eqref)
  (local $items (ref $vector))
  (if (ref.test (ref $values) (local.get $value))
    (then
      (local.set $items (struct.get $values 0 (ref.cast (ref $values) (local.get $value))))
      (if (i32.ne (array.len (local.get $items)) (i32.const 1))
        (then (call $fail (i32.const 5))))
      (return (array.get $vector (local.get $items) (i32.const 0)))))
  (local.get $value))
(func $truthy (param $value eqref) (result i32)
  (i32.eqz (ref.eq (local.get $value) (global.get $false))))
(func $arity (param $arguments (ref $vector)) (param $required i32) (param $rest i32)
  (if (i32.or (i32.lt_u (array.len (local.get $arguments)) (local.get $required))
              (i32.and (i32.eqz (local.get $rest))
                       (i32.ne (array.len (local.get $arguments)) (local.get $required))))
    (then (call $fail (i32.const 4)))))
(func $apply (param $procedure eqref) (param $arguments (ref $vector)) (result eqref)
  (local $closure (ref $closure))
  (local.set $closure (ref.cast (ref $closure) (local.get $procedure)))
  (return_call_ref $call
    (struct.get $closure 1 (local.get $closure)) (local.get $arguments)
    (struct.get $closure 0 (local.get $closure))))
(func $rest (param $arguments (ref $vector)) (param $start i32) (result eqref)
  (local $index i32) (local $result eqref)
  (local.set $index (array.len (local.get $arguments)))
  (local.set $result (global.get $nil))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (local.get $start)))
    (local.set $index (i32.sub (local.get $index) (i32.const 1)))
    (local.set $result (struct.new $pair (array.get $vector (local.get $arguments) (local.get $index))
                                         (local.get $result)))
    (br $next)))
  (local.get $result))
(func $list_vector (param $list eqref) (result (ref $vector))
  (local $cursor eqref) (local $length i32) (local $result (ref $vector)) (local $index i32)
  (local.set $cursor (local.get $list))
  (block $counted (loop $count
    (br_if $counted (ref.eq (local.get $cursor) (global.get $nil)))
    (local.set $length (i32.add (local.get $length) (i32.const 1)))
    (local.set $cursor (struct.get $pair 1 (ref.cast (ref $pair) (local.get $cursor))))
    (br $count)))
  (local.set $result (array.new $vector (global.get $unspecified) (local.get $length)))
  (local.set $cursor (local.get $list))
  (block $done (loop $copy
    (br_if $done (i32.eq (local.get $index) (local.get $length)))
    (array.set $vector (local.get $result) (local.get $index)
      (struct.get $pair 0 (ref.cast (ref $pair) (local.get $cursor))))
    (local.set $cursor (struct.get $pair 1 (ref.cast (ref $pair) (local.get $cursor))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $copy)))
  (local.get $result))

;; ---- Numbers ----

(func $is_integer (param $value eqref) (result i32)
  (i32.or (ref.test (ref i31) (local.get $value))
          (ref.test (ref $integer) (local.get $value))))
(func $integer_value (param $value eqref) (result i64)
  (if (result i64) (ref.test (ref i31) (local.get $value))
    (then (i64.extend_i32_s (i31.get_s (ref.cast (ref i31) (local.get $value)))))
    (else
      (if (result i64) (ref.test (ref $integer) (local.get $value))
        (then (struct.get $integer 0 (ref.cast (ref $integer) (local.get $value))))
        (else (call $fail (i32.const 1)) unreachable)))))
(func $float_value (param $value eqref) (result f64)
  (if (result f64) (ref.test (ref $float) (local.get $value))
    (then (struct.get $float 0 (ref.cast (ref $float) (local.get $value))))
    (else (f64.convert_i64_s (call $integer_value (local.get $value))))))
(func $pack_integer (param $value i64) (result eqref)
  (if (result eqref)
    (i32.and (i64.ge_s (local.get $value) (i64.const -1073741824))
             (i64.le_s (local.get $value) (i64.const 1073741823)))
    (then (ref.i31 (i32.wrap_i64 (local.get $value))))
    (else (struct.new $integer (local.get $value)))))
(func $pack_boolean (param $value i32) (result eqref)
  (if (result eqref) (local.get $value) (then (global.get $true)) (else (global.get $false))))

;; ---- Numeric ordering ----

;; Order values are -1, 0, 1; 2 denotes unordered (NaN).
(func $compare_float (param $a f64) (param $b f64) (result i32)
  (if (result i32) (f64.lt (local.get $a) (local.get $b)) (then (i32.const -1))
    (else (if (result i32) (f64.gt (local.get $a) (local.get $b)) (then (i32.const 1))
      (else (if (result i32) (f64.eq (local.get $a) (local.get $b))
        (then (i32.const 0)) (else (i32.const 2))))))))
(func $compare_integer (param $a i64) (param $b i64) (result i32)
  (if (result i32) (i64.lt_s (local.get $a) (local.get $b)) (then (i32.const -1))
    (else (i32.gt_s (i64.gt_s (local.get $a) (local.get $b)) (i32.const 0)))))
;; Match production comparison: do not round a large integer to f64 first.
(func $compare_integer_float (param $a i64) (param $b f64) (result i32)
  (local $whole i64) (local $order i32)
  (if (f64.ne (local.get $b) (local.get $b)) (then (return (i32.const 2))))
  (if (f64.ge (local.get $b) (f64.const 9223372036854775808)) (then (return (i32.const -1))))
  (if (f64.lt (local.get $b) (f64.const -9223372036854775808)) (then (return (i32.const 1))))
  (local.set $whole (i64.trunc_f64_s (local.get $b)))
  (local.set $order (call $compare_integer (local.get $a) (local.get $whole)))
  (if (result i32) (local.get $order) (then (local.get $order))
    (else (call $compare_float (f64.convert_i64_s (local.get $whole)) (local.get $b)))))
(func $compare (param $a eqref) (param $b eqref) (result i32)
  (local $order i32)
  (if (result i32) (call $is_integer (local.get $a))
    (then
      (if (result i32) (call $is_integer (local.get $b))
        (then (call $compare_integer (call $integer_value (local.get $a)) (call $integer_value (local.get $b))))
        (else (call $compare_integer_float (call $integer_value (local.get $a)) (call $float_value (local.get $b))))))
    (else
      (if (result i32) (call $is_integer (local.get $b))
        (then
          (local.set $order (call $compare_integer_float (call $integer_value (local.get $b)) (call $float_value (local.get $a))))
          (if (result i32) (i32.eq (local.get $order) (i32.const 2))
            (then (i32.const 2)) (else (i32.sub (i32.const 0) (local.get $order)))))
        (else (call $compare_float (call $float_value (local.get $a)) (call $float_value (local.get $b))))))))

(func $checked_add (param $a eqref) (param $b eqref) (result eqref)
      (local $x i64) (local $y i64) (local $n i64)
      (if (result eqref) (i32.and (call $is_integer (local.get $a)) (call $is_integer (local.get $b)))
        (then
          (local.set $x (call $integer_value (local.get $a)))
          (local.set $y (call $integer_value (local.get $b)))
          (local.set $n (i64.add (local.get $x) (local.get $y)))
          (if (i64.lt_s (i64.and (i64.xor (local.get $n) (local.get $x)) (i64.xor (local.get $n) (local.get $y))) (i64.const 0)) (then (call $fail (i32.const 2))))
          (call $pack_integer (local.get $n)))
        (else (struct.new $float (f64.add (call $float_value (local.get $a)) (call $float_value (local.get $b)))))))
(func $checked_subtract (param $a eqref) (param $b eqref) (result eqref)
      (local $x i64) (local $y i64) (local $n i64)
      (if (result eqref) (i32.and (call $is_integer (local.get $a)) (call $is_integer (local.get $b)))
        (then
          (local.set $x (call $integer_value (local.get $a)))
          (local.set $y (call $integer_value (local.get $b)))
          (local.set $n (i64.sub (local.get $x) (local.get $y)))
          (if (i64.lt_s (i64.and (i64.xor (local.get $x) (local.get $y)) (i64.xor (local.get $x) (local.get $n))) (i64.const 0)) (then (call $fail (i32.const 2))))
          (call $pack_integer (local.get $n)))
        (else (struct.new $float (f64.sub (call $float_value (local.get $a)) (call $float_value (local.get $b)))))))
(func $add (param $a eqref) (param $b eqref) (result eqref)
      (local $x i32) (local $y i32) (local $n i32) (local $order i32)
      (if (result eqref)
        (i32.and (ref.test (ref i31) (local.get $a)) (ref.test (ref i31) (local.get $b)))
        (then
          (local.set $x (i31.get_s (ref.cast (ref i31) (local.get $a))))
          (local.set $y (i31.get_s (ref.cast (ref i31) (local.get $b))))
          (local.set $n (i32.add (local.get $x) (local.get $y)))
          (if (result eqref) (i32.le_u (i32.add (local.get $n) (i32.const 1073741824)) (i32.const 2147483647))
            (then (ref.i31 (local.get $n))) (else (call $checked_add (local.get $a) (local.get $b)))))
        (else (call $checked_add (local.get $a) (local.get $b)))))
(func $subtract (param $a eqref) (param $b eqref) (result eqref)
      (local $x i32) (local $y i32) (local $n i32) (local $order i32)
      (if (result eqref)
        (i32.and (ref.test (ref i31) (local.get $a)) (ref.test (ref i31) (local.get $b)))
        (then
          (local.set $x (i31.get_s (ref.cast (ref i31) (local.get $a))))
          (local.set $y (i31.get_s (ref.cast (ref i31) (local.get $b))))
          (local.set $n (i32.sub (local.get $x) (local.get $y)))
          (if (result eqref) (i32.le_u (i32.add (local.get $n) (i32.const 1073741824)) (i32.const 2147483647))
            (then (ref.i31 (local.get $n))) (else (call $checked_subtract (local.get $a) (local.get $b)))))
        (else (call $checked_subtract (local.get $a) (local.get $b)))))
(func $numeric_equal (param $a eqref) (param $b eqref) (result eqref)
      (local $x i32) (local $y i32) (local $n i32) (local $order i32)
      (if (result eqref)
        (i32.and (ref.test (ref i31) (local.get $a)) (ref.test (ref i31) (local.get $b)))
        (then
          (local.set $x (i31.get_s (ref.cast (ref i31) (local.get $a))))
          (local.set $y (i31.get_s (ref.cast (ref i31) (local.get $b))))
          (call $pack_boolean (i32.eq (local.get $x) (local.get $y))))
        (else (local.set $order (call $compare (local.get $a) (local.get $b)))
          (call $pack_boolean (i32.and (i32.ne (local.get $order) (i32.const 2))
                                     (i32.eq (local.get $order) (i32.const 0)))))))
(func $less (param $a eqref) (param $b eqref) (result eqref)
      (local $x i32) (local $y i32) (local $n i32) (local $order i32)
      (if (result eqref)
        (i32.and (ref.test (ref i31) (local.get $a)) (ref.test (ref i31) (local.get $b)))
        (then
          (local.set $x (i31.get_s (ref.cast (ref i31) (local.get $a))))
          (local.set $y (i31.get_s (ref.cast (ref i31) (local.get $b))))
          (call $pack_boolean (i32.lt_s (local.get $x) (local.get $y))))
        (else (local.set $order (call $compare (local.get $a) (local.get $b)))
          (call $pack_boolean (i32.and (i32.ne (local.get $order) (i32.const 2))
                                     (i32.lt_s (local.get $order) (i32.const 0)))))))
(func $less_equal (param $a eqref) (param $b eqref) (result eqref)
      (local $x i32) (local $y i32) (local $n i32) (local $order i32)
      (if (result eqref)
        (i32.and (ref.test (ref i31) (local.get $a)) (ref.test (ref i31) (local.get $b)))
        (then
          (local.set $x (i31.get_s (ref.cast (ref i31) (local.get $a))))
          (local.set $y (i31.get_s (ref.cast (ref i31) (local.get $b))))
          (call $pack_boolean (i32.le_s (local.get $x) (local.get $y))))
        (else (local.set $order (call $compare (local.get $a) (local.get $b)))
          (call $pack_boolean (i32.and (i32.ne (local.get $order) (i32.const 2))
                                     (i32.le_s (local.get $order) (i32.const 0)))))))
(func $greater (param $a eqref) (param $b eqref) (result eqref)
      (local $x i32) (local $y i32) (local $n i32) (local $order i32)
      (if (result eqref)
        (i32.and (ref.test (ref i31) (local.get $a)) (ref.test (ref i31) (local.get $b)))
        (then
          (local.set $x (i31.get_s (ref.cast (ref i31) (local.get $a))))
          (local.set $y (i31.get_s (ref.cast (ref i31) (local.get $b))))
          (call $pack_boolean (i32.gt_s (local.get $x) (local.get $y))))
        (else (local.set $order (call $compare (local.get $a) (local.get $b)))
          (call $pack_boolean (i32.and (i32.ne (local.get $order) (i32.const 2))
                                     (i32.gt_s (local.get $order) (i32.const 0)))))))
(func $greater_equal (param $a eqref) (param $b eqref) (result eqref)
      (local $x i32) (local $y i32) (local $n i32) (local $order i32)
      (if (result eqref)
        (i32.and (ref.test (ref i31) (local.get $a)) (ref.test (ref i31) (local.get $b)))
        (then
          (local.set $x (i31.get_s (ref.cast (ref i31) (local.get $a))))
          (local.set $y (i31.get_s (ref.cast (ref i31) (local.get $b))))
          (call $pack_boolean (i32.ge_s (local.get $x) (local.get $y))))
        (else (local.set $order (call $compare (local.get $a) (local.get $b)))
          (call $pack_boolean (i32.and (i32.ne (local.get $order) (i32.const 2))
                                     (i32.ge_s (local.get $order) (i32.const 0)))))))
(func $multiply (param $a eqref) (param $b eqref) (result eqref)
  (local $x i64) (local $y i64) (local $product i64)
  (if (result eqref) (i32.and (call $is_integer (local.get $a)) (call $is_integer (local.get $b)))
    (then
      (local.set $x (call $integer_value (local.get $a)))
      (local.set $y (call $integer_value (local.get $b)))
      (if (i32.and (i64.eq (local.get $x) (i64.const -9223372036854775808))
                   (i64.eq (local.get $y) (i64.const -1))) (then (call $fail (i32.const 2))))
      (local.set $product (i64.mul (local.get $x) (local.get $y)))
      (if (i64.ne (local.get $y) (i64.const 0))
        (then (if (i64.ne (i64.div_s (local.get $product) (local.get $y)) (local.get $x))
                (then (call $fail (i32.const 2))))))
      (call $pack_integer (local.get $product)))
    (else (struct.new $float (f64.mul (call $float_value (local.get $a))
                                     (call $float_value (local.get $b)))))))
(func $checked_divisor (param $x i64) (param $y i64)
  (if (i64.eqz (local.get $y)) (then (call $fail (i32.const 9))))
  (if (i32.and (i64.eq (local.get $x) (i64.const -9223372036854775808))
               (i64.eq (local.get $y) (i64.const -1))) (then (call $fail (i32.const 2)))))
(func $divide (param $a eqref) (param $b eqref) (result eqref)
  (local $x i64) (local $y i64)
  (if (i32.and (call $is_integer (local.get $a)) (call $is_integer (local.get $b)))
    (then
      (local.set $x (call $integer_value (local.get $a)))
      (local.set $y (call $integer_value (local.get $b)))
      (call $checked_divisor (local.get $x) (local.get $y))
      (if (i64.eqz (i64.rem_s (local.get $x) (local.get $y)))
        (then (return (call $pack_integer (i64.div_s (local.get $x) (local.get $y))))))))
  (struct.new $float (f64.div (call $float_value (local.get $a)) (call $float_value (local.get $b)))))
(func $index (param $value eqref) (result i32)
  (local $integer i64)
  (local.set $integer (call $integer_value (local.get $value)))
  (if (i64.gt_u (local.get $integer) (i64.const 2147483647))
    (then (call $fail (i32.const 3))))
  (i32.wrap_i64 (local.get $integer)))

;; ---- Identity and predicates ----

(func $eq (param $a eqref) (param $b eqref) (result eqref)
  (call $pack_boolean (ref.eq (local.get $a) (local.get $b))))
(func $eqv (param $a eqref) (param $b eqref) (result eqref)
  (if (ref.eq (local.get $a) (local.get $b)) (then (return (global.get $true))))
  (if (i32.and (call $is_integer (local.get $a)) (call $is_integer (local.get $b)))
    (then (return (call $numeric_equal (local.get $a) (local.get $b)))))
  (if (i32.and (ref.test (ref $float) (local.get $a)) (ref.test (ref $float) (local.get $b)))
    (then (return (call $pack_boolean
      (f64.eq (struct.get $float 0 (ref.cast (ref $float) (local.get $a)))
               (struct.get $float 0 (ref.cast (ref $float) (local.get $b))))))))
  (if (i32.and (ref.test (ref $atom) (local.get $a)) (ref.test (ref $atom) (local.get $b)))
    (then (return (call $pack_boolean
      (i32.eq (struct.get $atom 0 (ref.cast (ref $atom) (local.get $a)))
               (struct.get $atom 0 (ref.cast (ref $atom) (local.get $b))))))))
  (global.get $false))
(func $is_number (param $value eqref) (result eqref)
  (call $pack_boolean (i32.or (call $is_integer (local.get $value))
                             (ref.test (ref $float) (local.get $value)))))
(func $is_integer_value (param $value eqref) (result eqref)
  (call $pack_boolean (call $is_integer (local.get $value))))
(func $is_null (param $value eqref) (result eqref)
  (call $eq (local.get $value) (global.get $nil)))
(func $is_boolean (param $value eqref) (result eqref)
  (call $pack_boolean (i32.or (ref.eq (local.get $value) (global.get $false))
                             (ref.eq (local.get $value) (global.get $true)))))
(func $is_text_kind (param $value eqref) (param $kind i32) (result eqref)
  (if (result eqref) (ref.test (ref $text_object) (local.get $value))
    (then (call $pack_boolean (i32.eq (struct.get $text_object 0
                                       (ref.cast (ref $text_object) (local.get $value)))
                                     (local.get $kind))))
    (else (global.get $false))))
(func $is_character (param $value eqref) (result eqref)
  (if (result eqref) (ref.test (ref $atom) (local.get $value))
    (then (call $pack_boolean (i32.ge_u (struct.get $atom 0
                                        (ref.cast (ref $atom) (local.get $value))) (i32.const 256))))
    (else (global.get $false))))
(func $character_value (param $value eqref) (result i32)
  (local $code i32)
  (local.set $code (struct.get $atom 0 (ref.cast (ref $atom) (local.get $value))))
  (if (i32.lt_u (local.get $code) (i32.const 256)) (then (call $fail (i32.const 8))))
  (i32.sub (local.get $code) (i32.const 256)))
(func $pack_character (param $code i32) (result eqref)
  (if (i32.or (i32.gt_u (local.get $code) (i32.const 1114111))
              (i32.le_u (i32.sub (local.get $code) (i32.const 55296)) (i32.const 2047)))
    (then (call $fail (i32.const 3))))
  (struct.new $atom (i32.add (local.get $code) (i32.const 256))))

;; ---- Pairs, vectors and values ----

(func $cons (param $a eqref) (param $b eqref) (result eqref)
  (struct.new $pair (local.get $a) (local.get $b)))
(func $car (param $value eqref) (result eqref)
  (struct.get $pair 0 (ref.cast (ref $pair) (local.get $value))))
(func $cdr (param $value eqref) (result eqref)
  (struct.get $pair 1 (ref.cast (ref $pair) (local.get $value))))
(func $builtin:values (param $arguments (ref $vector)) (result eqref)
  (if (result eqref) (i32.eq (array.len (local.get $arguments)) (i32.const 1))
    (then (array.get $vector (local.get $arguments) (i32.const 0)))
    (else (struct.new $values (local.get $arguments)))))
(func $builtin:call-with-values (param $arguments (ref $vector)) (result eqref)
  (local $result eqref) (local $values (ref $vector))
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (local.set $result (call $apply (array.get $vector (local.get $arguments) (i32.const 0))
                                  (array.new_fixed $vector 0)))
  (local.set $values
    (if (result (ref $vector)) (ref.test (ref $values) (local.get $result))
      (then (struct.get $values 0 (ref.cast (ref $values) (local.get $result))))
      (else (array.new_fixed $vector 1 (local.get $result)))))
  (return_call $apply (array.get $vector (local.get $arguments) (i32.const 1)) (local.get $values)))
(func $builtin:apply (param $arguments (ref $vector)) (result eqref)
  (local $prefix i32) (local $tail (ref $vector)) (local $all (ref $vector))
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $prefix (i32.sub (array.len (local.get $arguments)) (i32.const 2)))
  (local.set $tail (call $list_vector (array.get $vector (local.get $arguments)
                                     (i32.add (local.get $prefix) (i32.const 1)))))
  (local.set $all (array.new $vector (global.get $unspecified)
                    (i32.add (local.get $prefix) (array.len (local.get $tail)))))
  (array.copy $vector $vector (local.get $all) (i32.const 0)
    (local.get $arguments) (i32.const 1) (local.get $prefix))
  (array.copy $vector $vector (local.get $all) (local.get $prefix)
    (local.get $tail) (i32.const 0) (array.len (local.get $tail)))
  (return_call $apply (array.get $vector (local.get $arguments) (i32.const 0)) (local.get $all)))
(func $builtin:call/cc (param $arguments (ref $vector)) (result eqref)
  (call $fail (i32.const 7)) unreachable)
(func $builtin:call-with-current-continuation (param $arguments (ref $vector)) (result eqref)
  (return_call $builtin:call/cc (local.get $arguments)))

;; ---- Primitive entry points ----

(func $is_pair (param $value eqref) (result eqref)
  (call $pack_boolean (ref.test (ref $pair) (local.get $value))))

(func $is_procedure (param $value eqref) (result eqref)
  (call $pack_boolean (ref.test (ref $closure) (local.get $value))))

(func $is_vector (param $value eqref) (result eqref)
  (call $pack_boolean (ref.test (ref $vector) (local.get $value))))

(func $is_bytevector (param $value eqref) (result eqref)
  (call $pack_boolean (ref.test (ref $bytevector) (local.get $value))))

(func $builtin:eq? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (call $eq (array.get $vector (local.get $arguments) (i32.const 0)) (array.get $vector (local.get $arguments) (i32.const 1))))

(func $builtin:eqv? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (call $eqv (array.get $vector (local.get $arguments) (i32.const 0)) (array.get $vector (local.get $arguments) (i32.const 1))))

(func $builtin:cons (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (call $cons (array.get $vector (local.get $arguments) (i32.const 0)) (array.get $vector (local.get $arguments) (i32.const 1))))

(func $builtin:car (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $car (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:cdr (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $cdr (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:boolean? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_boolean (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:number? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_number (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:real? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_number (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:exact-integer? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_integer_value (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:pair? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_pair (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:null? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_null (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:procedure? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_procedure (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:vector? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_vector (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:bytevector? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_bytevector (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:char? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_character (array.get $vector (local.get $arguments) (i32.const 0))))

(func $builtin:string? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_text_kind (array.get $vector (local.get $arguments) (i32.const 0)) (i32.const 0)))

(func $builtin:symbol? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $is_text_kind (array.get $vector (local.get $arguments) (i32.const 0)) (i32.const 1)))

(func $builtin:inexact? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $pack_boolean (ref.test (ref $float) (array.get $vector (local.get $arguments) (i32.const 0)))))

(func $builtin:integer? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (if (result eqref) (ref.test (ref $float) (array.get $vector (local.get $arguments) (i32.const 0)))
    (then (call $pack_boolean (i32.and
      (f64.eq (f64.trunc (call $float_value (array.get $vector (local.get $arguments) (i32.const 0)))) (call $float_value (array.get $vector (local.get $arguments) (i32.const 0))))
      (f64.lt (f64.abs (call $float_value (array.get $vector (local.get $arguments) (i32.const 0)))) (f64.const inf)))))
    (else (call $is_integer_value (array.get $vector (local.get $arguments) (i32.const 0))))))

(func $builtin:+ (param $arguments (ref $vector)) (result eqref)
  (local $result eqref) (local $index i32)
  (call $arity (local.get $arguments) (i32.const 0) (i32.const 1))

  (local.set $result (call $pack_integer (i64.const 0)))
  (local.set $index (i32.const 0))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $result (call $add (local.get $result)
      (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (local.get $result))

(func $builtin:* (param $arguments (ref $vector)) (result eqref)
  (local $result eqref) (local $index i32)
  (call $arity (local.get $arguments) (i32.const 0) (i32.const 1))

  (local.set $result (call $pack_integer (i64.const 1)))
  (local.set $index (i32.const 0))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $result (call $multiply (local.get $result)
      (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (local.get $result))

(func $builtin:- (param $arguments (ref $vector)) (result eqref)
  (local $result eqref) (local $index i32)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 1))
  (if (i32.eq (array.len (local.get $arguments)) (i32.const 1))
    (then (return (call $subtract (call $pack_integer (i64.const 0)) (array.get $vector (local.get $arguments) (i32.const 0))))))
  (local.set $result (array.get $vector (local.get $arguments) (i32.const 0)))
  (local.set $index (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $result (call $subtract (local.get $result)
      (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (local.get $result))

(func $builtin:/ (param $arguments (ref $vector)) (result eqref)
  (local $result eqref) (local $index i32)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 1))
  (if (i32.eq (array.len (local.get $arguments)) (i32.const 1))
    (then (return (call $divide (call $pack_integer (i64.const 1)) (array.get $vector (local.get $arguments) (i32.const 0))))))
  (local.set $result (array.get $vector (local.get $arguments) (i32.const 0)))
  (local.set $index (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $result (call $divide (local.get $result)
      (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (local.get $result))

(func $builtin:= (param $arguments (ref $vector)) (result eqref)
  (local $index i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $index (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (if (i32.eqz (call $truthy (call $numeric_equal
          (array.get $vector (local.get $arguments) (i32.sub (local.get $index) (i32.const 1)))
          (array.get $vector (local.get $arguments) (local.get $index)))))
      (then (return (global.get $false))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (global.get $true))

(func $builtin:< (param $arguments (ref $vector)) (result eqref)
  (local $index i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $index (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (if (i32.eqz (call $truthy (call $less
          (array.get $vector (local.get $arguments) (i32.sub (local.get $index) (i32.const 1)))
          (array.get $vector (local.get $arguments) (local.get $index)))))
      (then (return (global.get $false))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (global.get $true))

(func $builtin:<= (param $arguments (ref $vector)) (result eqref)
  (local $index i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $index (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (if (i32.eqz (call $truthy (call $less_equal
          (array.get $vector (local.get $arguments) (i32.sub (local.get $index) (i32.const 1)))
          (array.get $vector (local.get $arguments) (local.get $index)))))
      (then (return (global.get $false))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (global.get $true))

(func $builtin:> (param $arguments (ref $vector)) (result eqref)
  (local $index i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $index (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (if (i32.eqz (call $truthy (call $greater
          (array.get $vector (local.get $arguments) (i32.sub (local.get $index) (i32.const 1)))
          (array.get $vector (local.get $arguments) (local.get $index)))))
      (then (return (global.get $false))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (global.get $true))

(func $builtin:>= (param $arguments (ref $vector)) (result eqref)
  (local $index i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $index (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (if (i32.eqz (call $truthy (call $greater_equal
          (array.get $vector (local.get $arguments) (i32.sub (local.get $index) (i32.const 1)))
          (array.get $vector (local.get $arguments) (local.get $index)))))
      (then (return (global.get $false))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (global.get $true))

(func $builtin:quotient (param $arguments (ref $vector)) (result eqref)
  (local $x i64) (local $y i64) (local $result i64)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (local.set $x (call $integer_value (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $y (call $integer_value (array.get $vector (local.get $arguments) (i32.const 1))))
  (call $checked_divisor (local.get $x) (local.get $y))
  (local.set $result (i64.div_s (local.get $x) (local.get $y)))

  (call $pack_integer (local.get $result)))

(func $builtin:remainder (param $arguments (ref $vector)) (result eqref)
  (local $x i64) (local $y i64) (local $result i64)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (local.set $x (call $integer_value (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $y (call $integer_value (array.get $vector (local.get $arguments) (i32.const 1))))
  (call $checked_divisor (local.get $x) (local.get $y))
  (local.set $result (i64.rem_s (local.get $x) (local.get $y)))

  (call $pack_integer (local.get $result)))

(func $builtin:modulo (param $arguments (ref $vector)) (result eqref)
  (local $x i64) (local $y i64) (local $result i64)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (local.set $x (call $integer_value (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $y (call $integer_value (array.get $vector (local.get $arguments) (i32.const 1))))
  (call $checked_divisor (local.get $x) (local.get $y))
  (local.set $result (i64.rem_s (local.get $x) (local.get $y)))
  (if (i32.and (i64.ne (local.get $result) (i64.const 0))
                        (i64.lt_s (i64.xor (local.get $result) (local.get $y)) (i64.const 0)))
    (then (local.set $result (i64.add (local.get $result) (local.get $y)))))
  (call $pack_integer (local.get $result)))

(func $builtin:set-car! (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (struct.set $pair 0 (ref.cast (ref $pair) (array.get $vector (local.get $arguments) (i32.const 0))) (array.get $vector (local.get $arguments) (i32.const 1)))
  (global.get $unspecified))

(func $builtin:set-cdr! (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (struct.set $pair 1 (ref.cast (ref $pair) (array.get $vector (local.get $arguments) (i32.const 0))) (array.get $vector (local.get $arguments) (i32.const 1)))
  (global.get $unspecified))

(func $builtin:vector (param $arguments (ref $vector)) (result eqref)
  (local.get $arguments))

(func $builtin:vector-length (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $pack_integer (i64.extend_i32_u (array.len (ref.cast (ref $vector) (array.get $vector (local.get $arguments) (i32.const 0)))))))

(func $builtin:vector-ref (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (array.get $vector (ref.cast (ref $vector) (array.get $vector (local.get $arguments) (i32.const 0))) (call $index (array.get $vector (local.get $arguments) (i32.const 1)))))

(func $builtin:vector-set! (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 3) (i32.const 0))
  (array.set $vector (ref.cast (ref $vector) (array.get $vector (local.get $arguments) (i32.const 0))) (call $index (array.get $vector (local.get $arguments) (i32.const 1))) (array.get $vector (local.get $arguments) (i32.const 2)))
  (global.get $unspecified))

(func $builtin:make-vector (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 1))
  (if (i32.gt_u (array.len (local.get $arguments)) (i32.const 2)) (then (call $fail (i32.const 4))))
  (array.new $vector
    (if (result eqref) (i32.eq (array.len (local.get $arguments)) (i32.const 2))
      (then (array.get $vector (local.get $arguments) (i32.const 1))) (else (global.get $unspecified))) (call $index (array.get $vector (local.get $arguments) (i32.const 0)))))

(func $builtin:char->integer (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $pack_integer (i64.extend_i32_u (call $character_value (array.get $vector (local.get $arguments) (i32.const 0))))))

(func $builtin:integer->char (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $pack_character (call $index (array.get $vector (local.get $arguments) (i32.const 0)))))

(func $builtin:char=? (param $arguments (ref $vector)) (result eqref)
  (local $index i32) (local $previous i32) (local $current i32) (local $matches i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $previous (call $character_value (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $index (i32.const 1))
  (local.set $matches (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $current (call $character_value (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $matches (i32.and (local.get $matches) (i32.eq (local.get $previous) (local.get $current))))
    (local.set $previous (local.get $current))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (call $pack_boolean (local.get $matches)))

(func $builtin:char<? (param $arguments (ref $vector)) (result eqref)
  (local $index i32) (local $previous i32) (local $current i32) (local $matches i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $previous (call $character_value (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $index (i32.const 1))
  (local.set $matches (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $current (call $character_value (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $matches (i32.and (local.get $matches) (i32.lt_u (local.get $previous) (local.get $current))))
    (local.set $previous (local.get $current))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (call $pack_boolean (local.get $matches)))

(func $builtin:char<=? (param $arguments (ref $vector)) (result eqref)
  (local $index i32) (local $previous i32) (local $current i32) (local $matches i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $previous (call $character_value (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $index (i32.const 1))
  (local.set $matches (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $current (call $character_value (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $matches (i32.and (local.get $matches) (i32.le_u (local.get $previous) (local.get $current))))
    (local.set $previous (local.get $current))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (call $pack_boolean (local.get $matches)))

(func $builtin:char>? (param $arguments (ref $vector)) (result eqref)
  (local $index i32) (local $previous i32) (local $current i32) (local $matches i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $previous (call $character_value (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $index (i32.const 1))
  (local.set $matches (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $current (call $character_value (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $matches (i32.and (local.get $matches) (i32.gt_u (local.get $previous) (local.get $current))))
    (local.set $previous (local.get $current))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (call $pack_boolean (local.get $matches)))

(func $builtin:char>=? (param $arguments (ref $vector)) (result eqref)
  (local $index i32) (local $previous i32) (local $current i32) (local $matches i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $previous (call $character_value (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $index (i32.const 1))
  (local.set $matches (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $current (call $character_value (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $matches (i32.and (local.get $matches) (i32.ge_u (local.get $previous) (local.get $current))))
    (local.set $previous (local.get $current))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (call $pack_boolean (local.get $matches)))

;; ---- Text and symbols ----

(func $string_text (param $value eqref) (result (ref $text))
  (local $object (ref $text_object))
  (local.set $object (ref.cast (ref $text_object) (local.get $value)))
  (if (i32.ne (struct.get $text_object 0 (local.get $object)) (i32.const 0))
    (then (call $fail (i32.const 8))))
  (struct.get $text_object 1 (local.get $object)))
(func $text_equal (param $a (ref $text)) (param $b (ref $text)) (result i32)
  (local $index i32)
  (if (i32.ne (array.len (local.get $a)) (array.len (local.get $b))) (then (return (i32.const 0))))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $a))))
    (if (i32.ne (array.get $text (local.get $a) (local.get $index))
                (array.get $text (local.get $b) (local.get $index))) (then (return (i32.const 0))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (i32.const 1))
(func $intern (param $text (ref $text)) (result eqref)
  (local $cursor eqref) (local $symbol eqref)
  (local.set $cursor (global.get $symbols))
  (block $new (loop $next
    (br_if $new (ref.is_null (local.get $cursor)))
    (local.set $symbol (call $car (local.get $cursor)))
    (if (call $text_equal (local.get $text)
          (struct.get $text_object 1 (ref.cast (ref $text_object) (local.get $symbol))))
      (then (return (local.get $symbol))))
    (local.set $cursor (call $cdr (local.get $cursor)))
    (br $next)))
  (local.set $symbol (struct.new $text_object (i32.const 1) (local.get $text)))
  (global.set $symbols (struct.new $pair (local.get $symbol) (global.get $symbols)))
  (local.get $symbol))
(func $builtin:string (param $arguments (ref $vector)) (result eqref)
  (local $text (ref $text)) (local $index i32)
  (local.set $text (array.new_default $text (array.len (local.get $arguments))))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (array.set $text (local.get $text) (local.get $index)
      (call $character_value (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (struct.new $text_object (i32.const 0) (local.get $text)))
(func $builtin:string-append (param $arguments (ref $vector)) (result eqref)
  (local $index i32) (local $length i32) (local $offset i32)
  (local $text (ref $text)) (local $part (ref $text))
  (block $counted (loop $count
    (br_if $counted (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $length (i32.add (local.get $length)
      (array.len (call $string_text (array.get $vector (local.get $arguments) (local.get $index))))))
    (local.set $index (i32.add (local.get $index) (i32.const 1))) (br $count)))
  (local.set $text (array.new_default $text (local.get $length)))
  (local.set $index (i32.const 0))
  (block $done (loop $copy
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $part (call $string_text (array.get $vector (local.get $arguments) (local.get $index))))
    (array.copy $text $text (local.get $text) (local.get $offset)
      (local.get $part) (i32.const 0) (array.len (local.get $part)))
    (local.set $offset (i32.add (local.get $offset) (array.len (local.get $part))))
    (local.set $index (i32.add (local.get $index) (i32.const 1))) (br $copy)))
  (struct.new $text_object (i32.const 0) (local.get $text)))
(func $builtin:substring (param $arguments (ref $vector)) (result eqref)
  (local $text (ref $text)) (local $start i32) (local $end i32) (local $result (ref $text))
  (call $arity (local.get $arguments) (i32.const 3) (i32.const 0))
  (local.set $text (call $string_text (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $start (call $index (array.get $vector (local.get $arguments) (i32.const 1))))
  (local.set $end (call $index (array.get $vector (local.get $arguments) (i32.const 2))))
  (if (i32.or (i32.gt_u (local.get $start) (local.get $end))
              (i32.gt_u (local.get $end) (array.len (local.get $text))))
    (then (call $fail (i32.const 3))))
  (local.set $result (array.new_default $text (i32.sub (local.get $end) (local.get $start))))
  (array.copy $text $text (local.get $result) (i32.const 0) (local.get $text)
    (local.get $start) (array.len (local.get $result)))
  (struct.new $text_object (i32.const 0) (local.get $result)))

;; ---- Bytevectors ----

(func $builtin:bytevector (param $arguments (ref $vector)) (result eqref)
  (local $bytes (ref $bytes)) (local $index i32) (local $value i32)
  (local.set $bytes (array.new_default $bytes (array.len (local.get $arguments))))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $value (call $index (array.get $vector (local.get $arguments) (local.get $index))))
    (if (i32.gt_u (local.get $value) (i32.const 255)) (then (call $fail (i32.const 3))))
    (array.set $bytes (local.get $bytes) (local.get $index) (local.get $value))
    (local.set $index (i32.add (local.get $index) (i32.const 1))) (br $next)))
  (struct.new $bytevector (local.get $bytes)))
(func $builtin:bytevector-u8-set! (param $arguments (ref $vector)) (result eqref)
  (local $value i32)
  (call $arity (local.get $arguments) (i32.const 3) (i32.const 0))
  (local.set $value (call $index (array.get $vector (local.get $arguments) (i32.const 2))))
  (if (i32.gt_u (local.get $value) (i32.const 255)) (then (call $fail (i32.const 3))))
  (array.set $bytes
    (struct.get $bytevector 0 (ref.cast (ref $bytevector)
      (array.get $vector (local.get $arguments) (i32.const 0))))
    (call $index (array.get $vector (local.get $arguments) (i32.const 1))) (local.get $value))
  (global.get $unspecified))

;; ---- Record types and instances ----

(func $field_index (param $type (ref $record_type)) (param $name eqref) (result i32)
  (local $index i32) (local $fields (ref $vector))
  (local.set $fields (struct.get $record_type 1 (local.get $type)))
  (loop $next
    (if (i32.eq (local.get $index) (array.len (local.get $fields)))
      (then (call $fail (i32.const 3))))
    (if (ref.eq (array.get $vector (local.get $fields) (local.get $index)) (local.get $name))
      (then (return (local.get $index))))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)) unreachable)
(func $record_fields (param $type eqref) (param $value eqref) (result (ref $vector))
  (local $record (ref $record))
  (local.set $record (ref.cast (ref $record) (local.get $value)))
  (if (i32.eqz (ref.eq (struct.get $record 0 (local.get $record)) (local.get $type)))
    (then (call $fail (i32.const 8))))
  (struct.get $record 1 (local.get $record)))
(func $builtin:%make-record (param $arguments (ref $vector)) (result eqref)
  (local $type (ref $record_type)) (local $names eqref) (local $values eqref)
  (local $fields (ref $vector))
  (call $arity (local.get $arguments) (i32.const 3) (i32.const 0))
  (local.set $type (ref.cast (ref $record_type) (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $names (array.get $vector (local.get $arguments) (i32.const 1)))
  (local.set $values (array.get $vector (local.get $arguments) (i32.const 2)))
  (local.set $fields (array.new $vector (global.get $unspecified)
                      (array.len (struct.get $record_type 1 (local.get $type)))))
  (block $done (loop $next
    (br_if $done (ref.eq (local.get $names) (global.get $nil)))
    (array.set $vector (local.get $fields) (call $field_index (local.get $type) (call $car (local.get $names)))
      (call $car (local.get $values)))
    (local.set $names (call $cdr (local.get $names)))
    (local.set $values (call $cdr (local.get $values))) (br $next)))
  (if (i32.eqz (ref.eq (local.get $values) (global.get $nil))) (then (call $fail (i32.const 4))))
  (struct.new $record (local.get $type) (local.get $fields)))


(func $builtin:string-length (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $pack_integer (i64.extend_i32_u (array.len (call $string_text (array.get $vector (local.get $arguments) (i32.const 0)))))))

(func $builtin:string-ref (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (call $pack_character (array.get $text (call $string_text (array.get $vector (local.get $arguments) (i32.const 0))) (call $index (array.get $vector (local.get $arguments) (i32.const 1))))))

(func $builtin:string=? (param $arguments (ref $vector)) (result eqref)
  (local $index i32) (local $previous (ref $text)) (local $current (ref $text)) (local $matches i32)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 1))
  (local.set $previous (call $string_text (array.get $vector (local.get $arguments) (i32.const 0))))
  (local.set $index (i32.const 1))
  (local.set $matches (i32.const 1))
  (block $done (loop $next
    (br_if $done (i32.eq (local.get $index) (array.len (local.get $arguments))))
    (local.set $current (call $string_text (array.get $vector (local.get $arguments) (local.get $index))))
    (local.set $matches (i32.and (local.get $matches) (call $text_equal (local.get $previous) (local.get $current))))
    (local.set $previous (local.get $current))
    (local.set $index (i32.add (local.get $index) (i32.const 1)))
    (br $next)))
  (call $pack_boolean (local.get $matches)))

(func $builtin:string->symbol (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $intern (call $string_text (array.get $vector (local.get $arguments) (i32.const 0)))))

(func $builtin:symbol->string (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (if (i32.eqz (call $truthy (call $is_text_kind (array.get $vector (local.get $arguments) (i32.const 0)) (i32.const 1))))
    (then (call $fail (i32.const 8))))
  (struct.new $text_object (i32.const 0) (struct.get $text_object 1 (ref.cast (ref $text_object) (array.get $vector (local.get $arguments) (i32.const 0))))))

(func $builtin:bytevector-length (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $pack_integer (i64.extend_i32_u (array.len (struct.get $bytevector 0 (ref.cast (ref $bytevector) (array.get $vector (local.get $arguments) (i32.const 0))))))))

(func $builtin:bytevector-u8-ref (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (call $pack_integer (i64.extend_i32_u (array.get_u $bytes (struct.get $bytevector 0 (ref.cast (ref $bytevector) (array.get $vector (local.get $arguments) (i32.const 0)))) (call $index (array.get $vector (local.get $arguments) (i32.const 1)))))))

(func $builtin:%make-record-type (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (struct.new $record_type (array.get $vector (local.get $arguments) (i32.const 0)) (call $list_vector (array.get $vector (local.get $arguments) (i32.const 1))) (i32.const 0)))

(func $builtin:%record? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 2) (i32.const 0))
  (if (result eqref) (ref.test (ref $record) (array.get $vector (local.get $arguments) (i32.const 1)))
    (then (call $pack_boolean (ref.eq (array.get $vector (local.get $arguments) (i32.const 0)) (struct.get $record 0 (ref.cast (ref $record) (array.get $vector (local.get $arguments) (i32.const 1)))))))
    (else (global.get $false))))

(func $builtin:%record-ref (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 3) (i32.const 0))
  (array.get $vector (call $record_fields (array.get $vector (local.get $arguments) (i32.const 0)) (array.get $vector (local.get $arguments) (i32.const 2))) (call $field_index (ref.cast (ref $record_type) (array.get $vector (local.get $arguments) (i32.const 0))) (array.get $vector (local.get $arguments) (i32.const 1)))))

(func $builtin:%record-set! (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 4) (i32.const 0))
  (array.set $vector (call $record_fields (array.get $vector (local.get $arguments) (i32.const 0)) (array.get $vector (local.get $arguments) (i32.const 2))) (call $field_index (ref.cast (ref $record_type) (array.get $vector (local.get $arguments) (i32.const 0))) (array.get $vector (local.get $arguments) (i32.const 1))) (array.get $vector (local.get $arguments) (i32.const 3)))
  (global.get $unspecified))

(func $builtin:eof-object? (param $arguments (ref $vector)) (result eqref)
  (call $arity (local.get $arguments) (i32.const 1) (i32.const 0))
  (call $pack_boolean (ref.eq (array.get $vector (local.get $arguments) (i32.const 0)) (global.get $eof))))
