(module
  (type $box (struct (field (mut i64)) (field (mut eqref))))
  (type $refs (array (mut eqref)))
  (type $bytes (array (mut i8)))
  (type $short (func (param i32 eqref) (result eqref)))
  (type $integer (func (param i32) (result i32)))
  (type $different (func (param i64) (result i64)))
  (memory $memory 1 2)
  (table $roots 1 4 eqref)
  (table $functions 2 2 funcref)
  (elem (table $functions) (i32.const 0) func $increment $identity64)
  (data (i32.const 7) "\00\7f\80\ff")
  (global $mutable (ref $box) (struct.new $box (i64.const 10) (ref.null eq)))

  ;; ---- Tail ABI and live native roots ----

  ;; Increasing and decreasing stack argument areas must both be constant space.
  ;; Mixed integer/reference/float arguments catch ABI register-class mistakes.
  (func $short (type $short) (param $n i32) (param $keep eqref) (result eqref)
    (if (result eqref) (i32.eqz (local.get $n))
      (then (local.get $keep))
      (else (return_call $wide (i32.sub (local.get $n) (i32.const 1))
        (local.get $keep) (i64.const 11) (i64.const 12) (i64.const 13)
        (i64.const 14) (i64.const 15) (i64.const 16) (i64.const 17)
        (f64.const 1.25) (f32.const 0.1)))))
  (func $wide (param $n i32) (param $keep eqref)
    (param $a i64) (param $b i64) (param $c i64) (param $d i64)
    (param $e i64) (param $f i64) (param $g i64)
    (param $h f64) (param $i f32) (result eqref)
    (if (i64.ne (i64.add (local.get $a) (local.get $g)) (i64.const 28)) (then unreachable))
    (if (i64.ne (i64.add (local.get $b) (local.get $f)) (i64.const 28)) (then unreachable))
    (if (i64.ne (i64.add (local.get $c) (local.get $e)) (i64.const 28)) (then unreachable))
    (if (i64.ne (local.get $d) (i64.const 14)) (then unreachable))
    (if (f64.ne (local.get $h) (f64.const 1.25)) (then unreachable))
    (if (f32.ne (local.get $i) (f32.const 0.1)) (then unreachable))
    (return_call_ref $short (local.get $n) (local.get $keep) (ref.func $short)))
  (func (export "tail") (param $n i32) (result i64)
    (struct.get $box 0 (ref.cast (ref $box)
      (call $short (local.get $n) (struct.new $box (i64.const 42) (ref.null eq))))))
  (func (export "root") (param $n i32) (result i64)
    (local $value (ref $box))
    (local.set $value (struct.new $box (i64.const 99) (ref.null eq)))
    (loop $allocate
      (drop (array.new $refs (local.get $value) (i32.const 100)))
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $allocate (local.get $n)))
    (struct.get $box 0 (local.get $value)))

  ;; ---- Containers, branch values and numeric edges ----

  (func $increment (type $integer) (param $n i32) (result i32)
    (i32.add (local.get $n) (i32.const 1)))
  (func $identity64 (type $different) (param $n i64) (result i64) (local.get $n))
  (func (export "i31-s") (param $n i32) (result i32) (i31.get_s (ref.i31 (local.get $n))))
  (func (export "i31-u") (param $n i32) (result i32) (i31.get_u (ref.i31 (local.get $n))))
  (func (export "check") (result i32)
    (local $bytes (ref $bytes)) (local $refs (ref $refs)) (local $n i32)
    (struct.set $box 0 (global.get $mutable) (i64.const 20))
    (if (i64.ne (struct.get $box 0 (global.get $mutable)) (i64.const 20)) (then unreachable))
    (local.set $bytes (array.new $bytes (i32.const 255) (i32.const 3)))
    (if (i32.ne (array.get_s $bytes (local.get $bytes) (i32.const 0)) (i32.const -1)) (then unreachable))
    (if (i32.ne (array.get_u $bytes (local.get $bytes) (i32.const 0)) (i32.const 255)) (then unreachable))
    (local.set $refs (array.new_fixed $refs 3 (ref.i31 (i32.const 10)) (ref.i31 (i32.const 20)) (ref.null eq)))
    (array.copy $refs $refs (local.get $refs) (i32.const 1) (local.get $refs) (i32.const 0) (i32.const 2))
    (if (i32.ne (i31.get_s (ref.cast (ref i31) (array.get $refs (local.get $refs) (i32.const 2)))) (i32.const 20)) (then unreachable))
    (if (i32.ne (table.grow $roots (global.get $mutable) (i32.const 2)) (i32.const 1)) (then unreachable))
    (if (i32.ne (table.grow $roots (ref.null eq) (i32.const 2)) (i32.const -1)) (then unreachable))
    (if (i32.eqz (ref.eq (table.get $roots (i32.const 2)) (global.get $mutable))) (then unreachable))
    (if (i32.ne (call_indirect $functions (type $integer) (i32.const 41) (i32.const 0)) (i32.const 42)) (then unreachable))
    (local.set $n (block $value (result i32) (br $value (i32.const 42)) (i32.const 0)))
    (if (i32.ne (local.get $n) (i32.const 42)) (then unreachable))
    (if (i32.eqz (ref.test (ref null i31) (ref.null eq))) (then unreachable))
    (if (ref.test (ref i31) (ref.null eq)) (then unreachable))
    (if (ref.test (ref null i31) (global.get $mutable)) (then unreachable))
    (if (i32.ne (i32.load8_s (i32.const 9)) (i32.const -128)) (then unreachable))
    (i64.store align=1 (i32.const 1) (i64.const 123456789))
    (if (i64.ne (i64.load align=1 (i32.const 1)) (i64.const 123456789)) (then unreachable))
    (memory.copy (i32.const 2) (i32.const 1) (i32.const 8))
    (if (i64.ne (i64.load align=1 (i32.const 2)) (i64.const 123456789)) (then unreachable))
    (if (i32.ne (memory.grow (i32.const 1)) (i32.const 1)) (then unreachable))
    (if (i32.ne (memory.grow (i32.const 1)) (i32.const -1)) (then unreachable))
    (if (i32.ne (i32.load8_u (i32.const 65536)) (i32.const 0)) (then unreachable))
    (if (i32.ne (i32.shr_u (i32.const -1) (i32.const 32)) (i32.const -1)) (then unreachable))
    (if (i64.ne (i64.rem_s (i64.const -9223372036854775808) (i64.const -1)) (i64.const 0)) (then unreachable))
    (if (i32.ne (i32.trunc_f64_u (f64.const -0.9)) (i32.const 0)) (then unreachable))
    (if (i32.ne (i32.ctz (i32.const 0)) (i32.const 32)) (then unreachable))
    (if (i64.ne (i64.reinterpret_f64 (f64.const -0)) (i64.const -9223372036854775808)) (then unreachable))
    (i32.const 0))
  (func (export "_start") (drop (call $short (i32.const 100) (ref.i31 (i32.const 42)))))

  ;; Each branch must trap without reading outside native storage or LLVM UB.
  (func (export "trap") (param $case i32)
    (if (i32.eq (local.get $case) (i32.const 0))
      (then (drop (i64.div_s (i64.const -9223372036854775808) (i64.const -1)))))
    (if (i32.eq (local.get $case) (i32.const 1))
      (then (drop (i32.div_u (i32.const 1) (i32.const 0)))))
    (if (i32.eq (local.get $case) (i32.const 2))
      (then (drop (i64.trunc_f64_s (f64.const 9223372036854775808)))))
    (if (i32.eq (local.get $case) (i32.const 3))
      (then (drop (i32.trunc_f64_u (f64.const nan)))))
    (if (i32.eq (local.get $case) (i32.const 4))
      (then (drop (i32.load offset=4294967295 (i32.const 1)))))
    (if (i32.eq (local.get $case) (i32.const 5))
      (then (drop (array.get $refs (array.new_default $refs (i32.const 1)) (i32.const 1)))))
    (if (i32.eq (local.get $case) (i32.const 6))
      (then (drop (array.len (ref.null $refs)))))
    (if (i32.eq (local.get $case) (i32.const 7))
      (then (drop (call_indirect $functions (type $integer) (i32.const 1) (i32.const 1)))))
    (if (i32.eq (local.get $case) (i32.const 8))
      (then (drop (ref.cast (ref $box) (ref.i31 (i32.const 0))))))
    (if (i32.eq (local.get $case) (i32.const 9))
      (then (drop (table.get $functions (i32.const 2)))))
    (if (i32.eq (local.get $case) (i32.const 10))
      (then (drop (call_ref $short (i32.const 0) (ref.null eq) (ref.null $short)))))
    (if (i32.eq (local.get $case) (i32.const 11))
      (then (memory.copy (i32.const 0) (i32.const 65536) (i32.const 1)))))
)
