(define-library (scheme cxr)
  (export caaar caadr cadar caddr cdaar cdadr cddar cdddr
          caaaar caaadr caadar caaddr cadaar cadadr caddar cadddr
          cdaaar cdaadr cdadar cdaddr cddaar cddadr cdddar cddddr)
  (import (scheme base))
  (begin
    (define (caaar value) (car (caar value)))
    (define (caadr value) (car (cadr value)))
    (define (cadar value) (car (cdar value)))
    (define (caddr value) (car (cddr value)))
    (define (cdaar value) (cdr (caar value)))
    (define (cdadr value) (cdr (cadr value)))
    (define (cddar value) (cdr (cdar value)))
    (define (cdddr value) (cdr (cddr value)))
    (define (caaaar value) (car (caaar value)))
    (define (caaadr value) (car (caadr value)))
    (define (caadar value) (car (cadar value)))
    (define (caaddr value) (car (caddr value)))
    (define (cadaar value) (car (cdaar value)))
    (define (cadadr value) (car (cdadr value)))
    (define (caddar value) (car (cddar value)))
    (define (cadddr value) (car (cdddr value)))
    (define (cdaaar value) (cdr (caaar value)))
    (define (cdaadr value) (cdr (caadr value)))
    (define (cdadar value) (cdr (cadar value)))
    (define (cdaddr value) (cdr (caddr value)))
    (define (cddaar value) (cdr (cdaar value)))
    (define (cddadr value) (cdr (cdadr value)))
    (define (cdddar value) (cdr (cddar value)))
    (define (cddddr value) (cdr (cdddr value)))))
