;; Scalar callable surface of the Rust runtime, expressed before linking.
;; These signatures exist in Wasm; native linkage is planned. Bodies are stubs.
(module
  ;; ---- Imports from compiled Scheme support ----

  (import "snail.awi" "retain" (func (param $root i32) (result i32)))
  (import "snail.awi" "release" (func (param $root i32)))
  (import "snail.awi" "kind" (func (param $root i32) (result i32)))
  (import "snail.awi" "same" (func (param $a i32) (param $b i32) (result i32)))
  (import "snail.awi" "call" (func (param $procedure i32) (param $arguments i32) (result i32)))
  (import "snail.awi" "integer" (func (param $value i64) (result i32)))
  (import "snail.awi" "real" (func (param $value f64) (result i32)))
  (import "snail.awi" "atom" (func (param $tag i32) (result i32)))
  (import "snail.awi" "pair" (func (param $car i32) (param $cdr i32) (result i32)))
  (import "snail.awi" "vector_new" (func (param $length i32) (result i32)))
  (import "snail.awi" "vector_set" (func (param $root i32) (param $index i32) (param $value i32)))
  (import "snail.awi" "string_new" (func (param $length i32) (result i32)))
  (import "snail.awi" "string_set" (func (param $root i32) (param $index i32) (param $value i32)))
  (import "snail.awi" "extension" (func (param $kind i32) (param $id i32) (result i32)))
  (import "snail.awi" "as_integer" (func (param $root i32) (result i64)))
  (import "snail.awi" "as_real" (func (param $root i32) (result f64)))
  (import "snail.awi" "atom_value" (func (param $root i32) (result i32)))
  (import "snail.awi" "length" (func (param $root i32) (result i32)))
  (import "snail.awi" "at" (func (param $root i32) (param $index i32) (result i32)))
  (import "snail.awi" "char_at" (func (param $root i32) (param $index i32) (result i32)))
  (import "snail.awi" "byte_at" (func (param $root i32) (param $index i32) (result i32)))
  (import "snail.awi" "car" (func (param $root i32) (result i32)))
  (import "snail.awi" "cdr" (func (param $root i32) (result i32)))
  (import "snail.awi" "extension_kind" (func (param $root i32) (result i32)))
  (import "snail.awi" "extension_id" (func (param $root i32) (result i32)))

  ;; ---- Scheme-callable runtime exports ----

  (func (export "snail:string->number") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:number->string") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:char-ci=?") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:char-alphabetic?") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:char-numeric?") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:char-whitespace?") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:error") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:open-input-file") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:open-output-file") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:file-exists?") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:close-port") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:read-char") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:read-string") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:open-output-string") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:get-output-string") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:display") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:write") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:newline") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:%current-input-port") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:%current-output-port") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:%current-error-port") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:%set-current-input-port!") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:%set-current-output-port!") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:%set-current-error-port!") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:command-line") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:exit") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:current-jiffy") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:jiffies-per-second") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:string-contains") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:%trace-begin") (param $arguments i32) (result i32) unreachable)
  (func (export "snail:%trace-end") (param $arguments i32) (result i32) unreachable)

  ;; ---- Initialization, diagnostics, and cleanup ----

  (func (export "_initialize") unreachable)
  (func (export "snail:fail") (param $code i32) (result i32) unreachable)
  (func (export "snail:drop-resource") (param $kind i32) (param $id i32) unreachable)
)
