[package]
name = "snail-example-extension"
version = "0.1.0"
edition = "2024"

[package.metadata.snail]
exports = ["rust-triple", "rust-remember", "rust-recalled", "rust-call", "rust-forget", "rust-root-stress"]

[dependencies]
snail-abi = { path = "../../abi" }
snail-awi = { path = "../../awi" }

[workspace]
