(define-library (tests actor)
  (export (rename increase add) value echo fail spin cycle procedure empty many
          shared nonprocedure macro)
  (import (scheme base))
  (begin
    (define count 0)
    (define nonprocedure 42)
    (define-syntax macro (syntax-rules () ((_ value) value)))
    (define (increase amount) (set! count (+ count amount)) count)
    (define (value) count)
    (define (echo value) value)
    (define (fail) (error "actor fixture failed"))
    (define (spin) (spin))
    (define (cycle)
      (let ((pair (cons 1 '()))) (set-cdr! pair pair) pair))
    (define (procedure) (lambda () 1))
    (define (empty) (values))
    (define (many) (values 1 2))
    (define (shared)
      (let ((item (list 1 2))) (vector item item)))))
