(import (scheme base) (scheme write))
(define (check expected actual)
  (if (not (equal? expected actual)) (error "bootstrap behavior mismatch" expected actual)))
(check '(3 1) (let-values (((x) (values 3)) ((y) (values 1))) (list x y)))
(check '(2 9) (let ((x 9)) (let-values (((x) (values 2)) ((y) (values x))) (list x y))))
(check '(1 (2 3)) (let-values (((x . rest) (values 1 2 3))) (list x rest)))
(check '(1 2 3) (let-values ((args (values 1 2 3))) args))
(check 'empty (let-values ((() (values))) 'empty))
(check 5 (let*-values (((x) (values 2)) ((y) (values (+ x 3)))) y))
(check 6 (let loop ((n 3) (sum 0)) (if (= n 0) sum (loop (- n 1) (+ sum n)))))
(check 3 (let loop ((loop 3)) loop))
(check 7 (let ((loop 7)) (let loop ((n loop)) n)))
(check 1 (let ((calls 0)) (case (begin (set! calls (+ calls 1)) 'a) (else #t)) calls))
(check 1 (let ((calls 0)) (or (begin (set! calls (+ calls 1)) 8) 9) calls))
(check 1 (let ((calls 0)) (cond ((begin (set! calls (+ calls 1)) 8) => (lambda (x) x))) calls))
(check '(a 1 2 3 . 4)
       (quasiquote (a (unquote 1) (unquote-splicing (list 2 3)) . (unquote 4))))
(check '#(a 2) (quasiquote #(a (unquote 2))))
(check '(quasiquote (x (unquote 3)))
       (quasiquote (quasiquote (x (unquote (unquote 3))))))
(define-record-type <box> (box y x) box? (x box-x set-box-x!) (y box-y))
(define box1 (box 2 1))
(check '(1 2 #t) (list (box-x box1) (box-y box1) (box? box1)))
(set-box-x! box1 9)
(check 9 (box-x box1))
(define (record-factory)
  (define-record-type <item> (item value) item? (value item-value))
  (list item item?))
(define first-type (record-factory))
(define second-type (record-factory))
(check #f ((cadr first-type) ((car second-type) 1)))
(check '(11 22 33) (map + '(1 2 3) '(10 20 30)))
(check '(1 2 . 3) (append '(1) '(2) 3))
(define cycle-a (cons 1 '()))
(define cycle-b (cons 1 '()))
(set-cdr! cycle-a cycle-a)
(set-cdr! cycle-b cycle-b)
(check #f (list? cycle-a))
(check #t (equal? cycle-a cycle-b))
(set-car! cycle-b 2)
(check #f (equal? cycle-a cycle-b))
(define converted 0)
(define p (make-parameter 1 (lambda (x) (set! converted (+ converted 1)) (+ x 10))))
(check 11 (p))
(check '(12 3)
       (call-with-values (lambda () (parameterize ((p 2)) (values (p) 3))) list))
(check 11 (p))
(check 2 converted)
(define q (make-parameter 3))
(check '(2 11) (parameterize ((p -8) (q (p))) (list (p) (q))))
(check 3 (q))
(define output (open-output-string))
(parameterize ((current-output-port output)) (display "hello") (newline))
(check "hello\n" (get-output-string output))
(define scalar-output (open-output-string))
(write-simple 4294967295 scalar-output)
(check "4294967295" (get-output-string scalar-output))
(check 1114111 (string->number "#x10ffff"))
(check -255 (string->number "#X-ff"))
(check 3 (string->number "#B+11"))
(check 15 (string->number "#o17"))
(check 19 (string->number "#d19"))
(check 16 (string->number "#x10" 2))
(check 1.5 (string->number "#D1.5" 16))
(check #f (string->number "#λ"))
(display "bootstrap checks passed\n")
