;; Specialize the VM instruction stream into LLVM control flow.
;; Instruction functions are Scheme-written LLVM and always inline into the
;; program. Rust supplies checked slot access, objects, allocation, and frames.
(define-library (snail-scheme llvm)
  (export write-llvm-program)
  (import (scheme base) (scheme cxr) (scheme write) (snail-scheme vm))
  (begin
    (define (line port . pieces)
      (for-each (lambda (piece) (display piece port)) pieces)
      (newline port))

    (define (for-indexed procedure items)
      (let loop ((items items) (index 0))
        (if (pair? items)
            (begin (procedure index (car items)) (loop (cdr items) (+ index 1))))))

    (define (write-llvm-program program port)
      (line port "; Generated by Snail-Scheme. VM state and values belong to Rust.")
      ;; Includes slot services and singleton tags; see runtime::PROGRAM_ABI.
      (line port "define i32 @snail_program_abi() { ret i32 1 }")
      (write-declarations port)
      (write-vm-instructions port)
      (write-data program port)
      (write-count "global" (length (vm-program-globals program)) port)
      (write-count "constant" (length (vm-program-constants program)) port)
      (write-execution program port))

    (define (write-count name count port)
      (line port "define i32 @snail_" name "_count() { ret i32 " count " }"))

    (define (write-declarations port)
      (line port "declare i32 @snail_rt_enter(ptr)")
      (line port "declare ptr @snail_rt_slot(ptr, i32, i32)")
      (line port "declare ptr @snail_rt_capture_slot(ptr, i32, i32)")
      (line port "declare ptr @snail_rt_single(ptr)")
      (line port "declare ptr @snail_rt_result(ptr)")
      (line port "declare ptr @snail_rt_push(ptr)")
      (line port "declare void @snail_rt_uninitialized(ptr)")
      (line port "declare void @snail_rt_close(ptr, i32, i32, i32, i32, i32)")
      (line port "declare i32 @snail_rt_call(ptr, i32, i32, i32)")
      (line port "declare i32 @snail_rt_return(ptr)")
      (line port "declare void @snail_halt(ptr)")
      (line port "declare void @snail_invalid_pc(ptr, i32)")
      (line port "declare void @snail_const_atom(ptr, i32, i32, ptr, i32)")
      (line port "declare void @snail_const_pair(ptr, i32, i32, i32)")
      (line port "declare void @snail_const_vector(ptr, i32, ptr, i32)")
      (line port "declare void @snail_global_primitive(ptr, i32, ptr, i32)"))

    ;; ---- Inline instruction bodies ---------------------------------------
    ;; Value is one machine word. On our integral-pointer targets, LLVM ptr
    ;; copies its bits at the target's width; it is NEVER dereferenced as a value.
    ;; These singleton encodings agree with runtime/object.rs and ABI tests.
    (define false-bits 14)
    (define unspecified-bits 38)
    (define uninitialized-bits 46)

    (define (write-vm-instructions port)
      (for-each (lambda (entry) (write-reference-handler (car entry) (cadr entry) port))
                '((constant 3) (refer_local 0) (refer_free 1) (refer_global 2)))
      (for-each (lambda (entry) (write-assignment-handler (car entry) (cadr entry) port))
                '((set_local 0) (set_free 1) (set_global 2)))
      (write-capture-handler 'capture_local 0 port)
      (write-capture-handler 'capture_free 1 port)
      (write-push-handler port)
      (write-test-handler port)
      (write-transfer-handlers port))

    ;; The entry check is the automatic safepoint. All slot operations after it
    ;; are GC-free. Load a source BEFORE a call that can resize its storage.
    (define (write-handler-entry name result arguments port)
      (line port "define internal " result " @snail_vm_" name "(ptr %vm" arguments
            ") alwaysinline {")
      (line port "entry:")
      (line port "  %ready = call i32 @snail_rt_enter(ptr %vm)")
      (line port "  %running = icmp ne i32 %ready, 0")
      (line port "  br i1 %running, label %body, label %done")
      (line port "body:"))

    (define (write-handler-exit result port)
      (line port "done:")
      (line port "  ret " result)
      (line port "}"))

    (define (write-checked-pointer name expression port)
      (line port "  %" name " = call ptr " expression)
      (line port "  %" name "_missing = icmp eq ptr %" name ", null")
      (line port "  br i1 %" name "_missing, label %done, label %" name "_ok")
      (line port name "_ok:"))

    (define (slot-expression index kind)
      (string-append "@snail_rt_slot(ptr %vm, i32 " index ", i32 "
                     (number->string kind) ")"))

    (define (write-reference-handler name kind port)
      (write-handler-entry name "void" ", i32 %index" port)
      (write-checked-pointer "source" (slot-expression "%index" kind) port)
      (line port "  %value = load ptr, ptr %source")
      (write-initialized-check port)
      (write-checked-pointer "destination" "@snail_rt_result(ptr %vm)" port)
      (line port "  store ptr %value, ptr %destination")
      (line port "  br label %done")
      (write-handler-exit "void" port))

    (define (write-initialized-check port)
      (line port "  %uninitialized = icmp eq ptr %value, inttoptr (i64 "
            uninitialized-bits " to ptr)")
      (line port "  br i1 %uninitialized, label %unbound, label %initialized")
      (line port "unbound:")
      (line port "  call void @snail_rt_uninitialized(ptr %vm)")
      (line port "  br label %done")
      (line port "initialized:"))

    (define (write-assignment-handler name kind port)
      (write-handler-entry name "void" ", i32 %index" port)
      (write-checked-pointer "source" "@snail_rt_single(ptr %vm)" port)
      (line port "  %value = load ptr, ptr %source")
      (write-checked-pointer "destination" (slot-expression "%index" kind) port)
      (line port "  store ptr %value, ptr %destination")
      (write-unspecified-result port)
      (write-handler-exit "void" port))

    (define (write-unspecified-result port)
      (write-checked-pointer "result" "@snail_rt_result(ptr %vm)" port)
      (line port "  store ptr inttoptr (i64 " unspecified-bits " to ptr), ptr %result")
      (line port "  br label %done"))

    (define (write-capture-handler name free port)
      (write-handler-entry name "void" ", i32 %index" port)
      (write-checked-pointer
       "source" (string-append "@snail_rt_capture_slot(ptr %vm, i32 %index, i32 "
                               (number->string free) ")") port)
      (write-push-value port)
      (write-handler-exit "void" port))

    (define (write-push-handler port)
      (write-handler-entry 'push "void" "" port)
      (write-checked-pointer "source" "@snail_rt_single(ptr %vm)" port)
      (write-push-value port)
      (write-handler-exit "void" port))

    (define (write-push-value port)
      (line port "  %value = load ptr, ptr %source")
      (write-checked-pointer "destination" "@snail_rt_push(ptr %vm)" port)
      (line port "  store ptr %value, ptr %destination")
      (line port "  br label %done"))

    (define (write-test-handler port)
      (write-handler-entry 'test "i32" "" port)
      (write-checked-pointer "source" "@snail_rt_single(ptr %vm)" port)
      (line port "  %value = load ptr, ptr %source")
      (line port "  %truth = icmp ne ptr %value, inttoptr (i64 " false-bits " to ptr)")
      (line port "  %answer = zext i1 %truth to i32")
      (line port "  ret i32 %answer")
      (write-handler-exit "i32 0" port))

    ;; Rust owns variable-size captures and frames. Control transfers return a
    ;; label to LLVM rather than entering Scheme recursively through Rust.
    (define (write-transfer-handlers port)
      (write-close-handler port)
      (write-handler-entry 'call "i32" ", i32 %argc, i32 %resume, i32 %tail" port)
      (line port "  %next = call i32 @snail_rt_call(ptr %vm, i32 %argc, i32 %resume, i32 %tail)")
      (line port "  ret i32 %next")
      (write-handler-exit "i32 4294967295" port)
      (write-handler-entry 'return "i32" "" port)
      (line port "  %next = call i32 @snail_rt_return(ptr %vm)")
      (line port "  ret i32 %next")
      (write-handler-exit "i32 4294967295" port))

    (define (write-close-handler port)
      (write-handler-entry 'close "void"
                           ", i32 %code, i32 %required, i32 %rest, i32 %locals, i32 %captures" port)
      (line port "  call void @snail_rt_close(ptr %vm, i32 %code, i32 %required,"
            " i32 %rest, i32 %locals, i32 %captures)")
      (line port "  br label %done")
      (write-handler-exit "void" port))

    ;; ---- Constant data and initialization --------------------------------

    (define (write-data program port)
      (for-indexed (lambda (index constant) (write-constant-data index constant port))
                   (vm-program-constants program))
      (for-each (lambda (primitive)
                  (write-bytes (string-append "p" (number->string (car primitive)))
                               (utf8-bytes (symbol->string (cdr primitive))) port))
                (vm-program-primitives program)))

    (define (write-constant-data index constant port)
      (case (constant-kind constant)
        ((pair) #f)
        ((vector) (write-indices index (constant-data constant) port))
        (else (write-bytes (string-append "c" (number->string index))
                           (constant-bytes constant) port))))

    (define (write-bytes name bytes port)
      (display (string-append "@" name " = private constant ["
                              (number->string (length bytes)) " x i8] c\"") port)
      (for-each (lambda (byte)
                  (display "\\" port)
                  (display (string-ref "0123456789ABCDEF" (quotient byte 16)) port)
                  (display (string-ref "0123456789ABCDEF" (modulo byte 16)) port)) bytes)
      (line port "\", align 1"))

    (define (write-indices index indices port)
      (display (string-append "@c" (number->string index) " = private constant ["
                              (number->string (length indices)) " x i32] [") port)
      (let loop ((indices indices))
        (if (pair? indices)
            (begin (display "i32 " port) (display (car indices) port)
                   (if (pair? (cdr indices)) (display ", " port))
                   (loop (cdr indices)))))
      (line port "], align 4"))

    (define (utf8-bytes text)
      (apply append (map (lambda (character) (encode-codepoint (char->integer character)))
                         (string->list text))))

    (define (encode-codepoint code)
      (cond ((< code 128) (list code))
            ((< code 2048)
             (list (+ 192 (quotient code 64)) (+ 128 (modulo code 64))))
            ((< code 65536)
             (list (+ 224 (quotient code 4096))
                   (+ 128 (modulo (quotient code 64) 64)) (+ 128 (modulo code 64))))
            (else
             (list (+ 240 (quotient code 262144)) (+ 128 (modulo (quotient code 4096) 64))
                   (+ 128 (modulo (quotient code 64) 64)) (+ 128 (modulo code 64))))))

    (define (constant-bytes constant)
      (let ((data (constant-data constant)))
        (case (constant-kind constant)
          ((string) (utf8-bytes data))
          ((symbol) (utf8-bytes (symbol->string data)))
          ((integer float) (utf8-bytes (number->string data)))
          ((character) (utf8-bytes (number->string (char->integer data))))
          ((boolean) (list (if data 49 48)))
          ((bytevector) (bytevector-bytes data))
          ((nil unspecified) '())
          (else (error "constant has no byte representation" (constant-kind constant))))))

    (define (bytevector-bytes bytes)
      (let loop ((index 0))
        (if (= index (bytevector-length bytes)) '()
            (cons (bytevector-u8-ref bytes index) (loop (+ index 1))))))

    (define (atom-kind kind)
      (case kind
        ((string) 0) ((symbol) 1) ((integer) 2) ((float) 3) ((character) 4)
        ((boolean) 5) ((nil) 6) ((bytevector) 7) ((unspecified) 8)
        (else (error "unknown constant kind" kind))))

    (define (write-execution program port)
      (line port "define void @snail_program(ptr %vm) {")
      (line port "entry:")
      (write-initialization program port)
      (line port "  br label %dispatch")
      (for-each (lambda (instruction) (write-instruction instruction port))
                (vm-program-instructions program))
      (write-dispatch program port)
      (write-exit port))

    (define (write-exit port)
      (line port "invalid:")
      (line port "  call void @snail_invalid_pc(ptr %vm, i32 %pc)")
      (line port "  br label %done")
      (line port "done:")
      (line port "  call void @snail_halt(ptr %vm)")
      (line port "  ret void")
      (line port "}"))

    (define (write-initialization program port)
      (for-indexed (lambda (index constant) (write-constant-init index constant port))
                   (vm-program-constants program))
      (for-each (lambda (primitive) (write-primitive-init primitive port))
                (vm-program-primitives program))
      (line port "  call void @snail_vm_close(ptr %vm, i32 " (vm-program-entry program)
            ", i32 0, i32 0, i32 " (vm-program-locals program) ", i32 0)")
      (line port "  %start = call i32 @snail_vm_call(ptr %vm, i32 0, i32 4294967295, i32 1)"))

    (define (write-constant-init index constant port)
      (let ((data (constant-data constant)))
        (case (constant-kind constant)
          ((pair) (line port "  call void @snail_const_pair(ptr %vm, i32 " index
                        ", i32 " (car data) ", i32 " (cadr data) ")"))
          ((vector) (line port "  call void @snail_const_vector(ptr %vm, i32 " index
                          ", ptr @c" index ", i32 " (length data) ")"))
          (else (line port "  call void @snail_const_atom(ptr %vm, i32 " index
                      ", i32 " (atom-kind (constant-kind constant)) ", ptr @c" index
                      ", i32 " (length (constant-bytes constant)) ")")))))

    (define (write-primitive-init primitive port)
      (line port "  call void @snail_global_primitive(ptr %vm, i32 " (car primitive)
            ", ptr @p" (car primitive) ", i32 "
            (length (utf8-bytes (symbol->string (cdr primitive)))) ")"))

    (define (handler-name operation)
      (list->string (map (lambda (character) (if (char=? character #\-) #\_ character))
                         (string->list (symbol->string operation)))))

    (define (write-handler-call prefix instruction port)
      (display (string-append "  " prefix " @snail_vm_"
                              (handler-name (instruction-operation instruction)) "(ptr %vm") port)
      (for-each (lambda (operand) (display ", i32 " port) (display operand port))
                (instruction-operands instruction))
      (line port ")"))

    (define (write-instruction instruction port)
      (let ((label (instruction-label instruction)))
        (line port "b" label ":")
        (case (instruction-operation instruction)
          ((test) (write-test instruction port))
          ((call return)
           (write-handler-call (string-append "%next" (number->string label) " = call i32")
                               instruction port)
           (line port "  br label %dispatch"))
          (else
           (write-handler-call "call void" instruction port)
           (line port "  br label %b" (instruction-next instruction))))))

    (define (write-test instruction port)
      (let ((label (instruction-label instruction)) (arms (instruction-operands instruction)))
        (line port "  %truth" label " = call i32 @snail_vm_test(ptr %vm)")
        (line port "  %test" label " = icmp ne i32 %truth" label ", 0")
        (line port "  br i1 %test" label ", label %b" (car arms) ", label %b" (cadr arms))))

    (define (write-dispatch program port)
      (line port "dispatch:")
      (write-destinations program port)
      (line port "  switch i32 %pc, label %invalid [")
      (line port "    i32 4294967295, label %done")
      (for-each (lambda (label) (line port "    i32 " label ", label %b" label))
                (dispatch-targets program))
      (line port "  ]"))

    (define (write-destinations program port)
      (display "  %pc = phi i32 [ %start, %entry ]" port)
      (for-each (lambda (instruction)
                  (if (memq (instruction-operation instruction) '(call return))
                      (let ((label (instruction-label instruction)))
                        (display (string-append ", [ %next" (number->string label)
                                                ", %b" (number->string label) " ]") port))))
                (vm-program-instructions program))
      (newline port))

    ;; Only procedure entries and non-tail return addresses need dynamic lookup.
    ;; A return address needs a case even when no static branch targets it.
    (define (dispatch-targets program)
      (let loop ((instructions (vm-program-instructions program))
                 (targets (list (vm-program-entry program))))
        (if (null? instructions) (reverse targets)
            (let ((target (instruction-destination (car instructions))))
              (loop (cdr instructions)
                    (if (and target (not (memv target targets))) (cons target targets) targets))))))

    (define (instruction-destination instruction)
      (let ((args (instruction-operands instruction)))
        (case (instruction-operation instruction)
          ((close) (car args))
          ((call) (if (= (caddr args) 0) (cadr args) #f))
          (else #f))))))
