;; Lower resolved Scheme into explicit structured machine operations. Binding identities choose
;; storage; printed names are only diagnostics. Assigned lexical bindings are
;; cells; immutable captures are values. Frames and arguments share one stack.
(define-library (snail-scheme lower)
  (export hir-library->mir-library)
  (import (snail-scheme trace) (scheme base) (scheme cxr)
          (prefix (snail-scheme hir) hir:) (prefix (snail-scheme library) library:)
          (prefix (snail-scheme mir) mir:) (snail-scheme machine))
  (begin
    ;; These rewrites require an immutable core binding and exact source arity.
    (define direct-primitives
      '((+ 2 add) (- 2 subtract) (= 2 numeric-equal) (< 2 less)
        (<= 2 less-equal) (> 2 greater) (>= 2 greater-equal)
        (procedure? 1 procedure-predicate) (number? 1 number-predicate)
        (exact-integer? 1 integer-predicate)))

    (define-record-type <builder>
      (make-builder globals primitives boxed machine definitions constants next-constant)
      builder?
      (globals builder-globals)
      (primitives builder-primitives)
      (boxed builder-boxed)
      (machine builder-machine)
      (definitions builder-definitions set-builder-definitions!)
      (constants builder-constants set-builder-constants!)
      (next-constant builder-next-constant set-builder-next-constant!))

    ;; ---- Library elaboration ----

    (define-traced (hir-library->mir-library root)
      (let* ((libraries (library:library-dependency-order root))
             (items (apply append (map library:library-body libraries)))
             (primitives (apply append (map library-primitives libraries)))
             (globals (apply append (map library-global-definitions libraries)))
             (locals (local-definitions items globals))
             (builder (make-builder (numbered globals) (immutable-primitives primitives items)
                                    (boxed-definitions items globals) (create-machine) '() '() 0))
             (entries (map (lambda (library)
                             (cons library (mir:make-code (or (library:library-name library) "entry")))) libraries)))
        (lower-libraries libraries entries locals builder)))

    ;; All initializers share the root Scheme frame; only the script's final
    ;; expression is in tail position. Each library owns its emitted code/data.
    (define (lower-libraries libraries entries locals builder)
      (let loop ((remaining libraries) (lowered '()))
        (let* ((library (car remaining))
               (body (lower-library-body library (cdr remaining) entries locals builder (null? lowered)))
               (result (rebuild-library library body lowered)))
          (if (null? (cdr remaining)) result
              (loop (cdr remaining) (cons (cons library result) lowered))))))

    (define (lower-library-body library following entries locals builder first?)
      (set-builder-definitions! builder '())
      (set-builder-constants! builder '())
      (let* ((next (if (null? following) (emit! builder 'return '() #f #f)
                       (mir:call-direct (cdr (assq (car following) entries)) '() #t)))
             (body (lower-items (library:library-body library) (storage-environment locals '())
                                builder next (null? following)))
             (entry (if first? (lower-boxes locals builder body #f) body))
             (code (cdr (assq library entries))))
        (finish-library-body library code entry builder (null? following))))

    (define (finish-library-body library code entry builder last?)
      (let ((globals (library-global-definitions library)))
        (mir:make-body
         code (length (local-definitions (library:library-body library) globals))
         (append (if last? (machine-definitions (builder-machine builder)) '())
                 (reverse (builder-definitions builder)) (list (mir:make-definition code entry)))
         (reverse (builder-constants builder)) (map hir:value-definition-name globals)
         (map (lambda (definition)
                (cons (cdr (assq definition (builder-globals builder)))
                      (hir:value-definition-name definition))) (library-primitives library)))))

    ;; Rebuild only the container graph. Names, definitions, and source objects
    ;; keep their identities; every import points at its already-lowered library.
    (define (rebuild-library library body lowered)
      (library:make-library
       (library:library-name library)
       (map (lambda (declaration) (rebuild-import declaration lowered)) (library:library-imports library))
       (library:library-exports library) (library:library-dependencies library) body (library:library-loc library)))
    (define (rebuild-import declaration lowered)
      (library:make-import-declaration
       (map (lambda (library) (cdr (assq library lowered))) (library:import-declaration-libraries declaration))
       (library:import-declaration-bindings declaration) (library:import-declaration-source declaration)
       (library:import-declaration-loc declaration)))

    (define (library-global-definitions library)
      (unique-identities (append (library-primitives library) (item-definitions (library:library-body library)))))
    (define (library-primitives library)
      (if (equal? (library:library-name library) '(snail-scheme core))
          (value-exports (library:library-exports library)) '()))
    (define (value-exports exports)
      (if (null? exports) '()
          (let ((definition (library:named-binding-definition (car exports))))
            (if (hir:value-definition? definition)
                (cons definition (value-exports (cdr exports)))
                (value-exports (cdr exports))))))

    (define (item-definitions items)
      (if (null? items) '()
          (if (hir:value-binding? (car items))
              (cons (hir:value-binding-definition (car items))
                    (item-definitions (cdr items)))
              (item-definitions (cdr items)))))

    (define (unique-identities definitions)
      (let loop ((remaining definitions) (seen '()) (result '()))
        (cond ((null? remaining) (reverse result))
              ((memq (car remaining) seen) (loop (cdr remaining) seen result))
              (else (loop (cdr remaining) (cons (car remaining) seen)
                          (cons (car remaining) result))))))

    (define (numbered values)
      (let loop ((values values) (index 0))
        (if (null? values) '()
            (cons (cons (car values) index) (loop (cdr values) (+ index 1))))))

    (define (storage-environment locals free)
      (append (map (lambda (entry) (cons (car entry) (cons 'local (cdr entry))))
                   (numbered locals))
              (map (lambda (entry) (cons (car entry) (cons 'free (cdr entry))))
                   (numbered free))))

    (define (storage definition environment builder)
      (let ((local (assq definition environment))
            (global (assq definition (builder-globals builder))))
        (cond (local (cdr local))
              (global (cons 'global (cdr global)))
              (else (error "binding has no VM storage"
                           (hir:value-definition-name definition)
                           (hir:value-definition-loc definition))))))

    ;; Descend through blocks in this activation, stopping at nested procedures.
    ;; Their binding identities belong to a different activation.
    (define (local-definitions items globals)
      (define (collect node)
        (cond ((hir:lambda? node) '())
              ((hir:value-binding? node)
               (append (if (memq (hir:value-binding-definition node) globals) '()
                           (list (hir:value-binding-definition node)))
                       (collect (hir:value-binding-initializer node))))
              (else (apply append (map collect (children node))))))
      (unique-identities (apply append (map collect items))))

    (define (children node)
      (cond
       ((hir:application? node)
        (cons (hir:application-operator node) (hir:application-operands node)))
       ((hir:block? node) (hir:block-items node))
       ((hir:conditional? node)
        (append (list (hir:conditional-test node) (hir:conditional-consequent node))
                (if (hir:conditional-opt-alternate node)
                    (list (hir:conditional-opt-alternate node)) '())))
       ((hir:assignment? node) (list (hir:assignment-target node) (hir:assignment-value node)))
       ((hir:value-binding? node) (list (hir:value-binding-initializer node)))
       (else '())))

    (define (lambda-locals procedure)
      (append (hir:lambda-parameters procedure)
              (if (hir:lambda-opt-rest-parameter procedure)
                  (list (hir:lambda-opt-rest-parameter procedure)) '())
              (local-definitions (list (hir:lambda-body procedure)) '())))

    ;; Descend into child procedures because their set! can assign an outer name.
    (define (assigned-definitions items)
      (define (visit node)
        (append
         (if (hir:assignment? node)
             (list (hir:name-definition (hir:assignment-target node))) '())
         (if (hir:lambda? node) (visit (hir:lambda-body node))
             (apply append (map visit (children node))))))
      (unique-identities (apply append (map visit items))))

    ;; A closure created before a definition's initializer must retain its
    ;; location, not copy UNINITIALIZED. Otherwise immutable locals stay unboxed.
    ;; The walk tracks definitely initialized identities through evaluation order;
    ;; branches keep only identities initialized on both paths.
    (define (boxed-definitions items globals)
      (define (nested node)
        (if (hir:lambda? node)
            (append (car (initialization-sequence (list (hir:lambda-body node))
                                                  (lambda-locals node) globals
                                                  (lambda-arguments node)))
                    (nested (hir:lambda-body node)))
            (apply append (map nested (children node)))))
      (unique-identities
       (append (assigned-definitions items)
               (car (initialization-sequence items (local-definitions items globals) globals '()))
               (apply append (map nested items)))))

    (define (lambda-arguments procedure)
      (append (hir:lambda-parameters procedure)
              (if (hir:lambda-opt-rest-parameter procedure)
                  (list (hir:lambda-opt-rest-parameter procedure)) '())))

    (define (initialization-sequence nodes locals globals initialized)
      (if (null? nodes) (cons '() initialized)
          (let* ((first (initialization-state (car nodes) locals globals initialized))
                 (rest (initialization-sequence (cdr nodes) locals globals (cdr first))))
            (cons (append (car first) (car rest)) (cdr rest)))))

    (define (uninitialized-captures procedure locals globals initialized)
      (let loop ((free (free-definitions procedure (numbered globals))))
        (cond ((null? free) '())
              ((and (memq (car free) locals) (not (memq (car free) initialized)))
               (cons (car free) (loop (cdr free))))
              (else (loop (cdr free))))))

    (define (initialization-state node locals globals initialized)
      (cond ((hir:lambda? node)
             (cons (uninitialized-captures node locals globals initialized) initialized))
            ((hir:value-binding? node)
             (let ((state (initialization-state (hir:value-binding-initializer node)
                                                locals globals initialized)))
               (cons (car state) (cons (hir:value-binding-definition node) (cdr state)))))
            ((hir:conditional? node) (conditional-initialization node locals globals initialized))
            ((hir:application? node)
             (initialization-sequence (append (hir:application-operands node)
                                              (list (hir:application-operator node)))
                                      locals globals initialized))
            (else (initialization-sequence (children node) locals globals initialized))))

    (define (conditional-initialization node locals globals initialized)
      (let* ((test (initialization-state (hir:conditional-test node) locals globals initialized))
             (yes (initialization-state (hir:conditional-consequent node) locals globals (cdr test)))
             (no (if (hir:conditional-opt-alternate node)
                     (initialization-state (hir:conditional-opt-alternate node) locals globals (cdr test))
                     (cons '() (cdr test)))))
        (cons (append (car test) (car yes) (car no))
              (let loop ((identities (cdr yes)))
                (cond ((null? identities) '())
                      ((memq (car identities) (cdr no))
                       (cons (car identities) (loop (cdr identities))))
                      (else (loop (cdr identities))))))))

    (define (lower-boxes locals builder next loc)
      (let loop ((remaining locals) (index 0))
        (if (null? remaining) next
            (let ((rest (loop (cdr remaining) (+ index 1))))
              (if (memq (car remaining) (builder-boxed builder))
                  (emit! builder 'box (list index) rest loc) rest)))))

    ;; Unlike local collection, capture analysis enters nested lambdas. A child
    ;; can need an outer cell even if its parent never reads it. Every lambda's
    ;; definitions are bound before visiting initializers, including recursive ones.
    (define (free-definitions procedure globals)
      (define (visit node bound)
        (cond
         ((hir:name? node)
          (let ((definition (hir:name-definition node)))
            (if (or (memq definition bound) (assq definition globals)) '()
                (list definition))))
         ((hir:lambda? node)
          (visit (hir:lambda-body node) (append (lambda-locals node) bound)))
         (else (apply append (map (lambda (child) (visit child bound)) (children node))))))
      (unique-identities (visit procedure '())))

    ;; The elaborator constructs immutable trees. Only resumable Scheme entries
    ;; receive code identities; ordinary instructions and branches have no labels.
    (define (emit! builder operation operands next loc)
      (machine-instruction (builder-machine builder) operation operands next))

    (define (define-code! builder name body)
      (let ((code (mir:make-code name)))
        (set-builder-definitions!
         builder (cons (mir:make-definition code body) (builder-definitions builder)))
        code))

    (define (add-constant! builder kind data)
      (let ((index (builder-next-constant builder)))
        (set-builder-next-constant! builder (+ index 1))
        (set-builder-constants! builder (cons (mir:make-constant kind data)
                                              (builder-constants builder)))
        index))

    (define (literal-constant! builder datum)
      (cond
       ((pair? datum)
        (let* ((head (literal-constant! builder (car datum)))
               (tail (literal-constant! builder (cdr datum))))
          (add-constant! builder 'pair (list head tail))))
       ((vector? datum)
        (add-constant! builder 'vector
                       (map (lambda (item) (literal-constant! builder item))
                            (vector->list datum))))
       ((null? datum) (add-constant! builder 'nil #f))
       ((boolean? datum) (add-constant! builder 'boolean datum))
       ((char? datum) (add-constant! builder 'character datum))
       ((string? datum) (add-constant! builder 'string datum))
       ((symbol? datum) (add-constant! builder 'symbol datum))
       ((bytevector? datum) (add-constant! builder 'bytevector datum))
       ((exact-integer? datum) (add-constant! builder 'integer datum))
       ((and (number? datum) (real? datum) (inexact? datum))
        (add-constant! builder 'float datum))
       (else (error "unsupported literal in baseline runtime" datum))))

    (define (lower-items items environment builder next tail?)
      (if (null? items) next
          (let ((rest (lower-items (cdr items) environment builder next tail?)))
            (lower (car items) environment builder rest (and tail? (null? (cdr items)))))))

    ;; Every expression replaces the result sequence. Nonfinal expressions need
    ;; no discard instruction; single-value checks belong to their receiving ops.

    (define (lower node environment builder next tail?)
      (cond
       ((hir:literal? node)
        (emit! builder 'constant (list (literal-constant! builder (hir:literal-value node)))
               next (hir:literal-loc node)))
       ((hir:name? node)
        (lower-reference node environment builder next))
       ((hir:lambda? node)
        (lower-lambda node environment builder next))
       ((hir:application? node)
        (lower-application node environment builder next tail?))
       ((hir:conditional? node)
        (lower-conditional node environment builder next tail?))
       ((hir:block? node)
        (lower-items (hir:block-items node)
                     environment builder next tail?))
       ((hir:value-binding? node)
        (lower-store (hir:value-binding-definition node) (hir:value-binding-initializer node)
                     environment builder next (hir:value-binding-loc node)))
       ((hir:assignment? node)
        (lower-store (hir:name-definition (hir:assignment-target node))
                     (hir:assignment-value node) environment builder next
                     (hir:assignment-loc node)))
       (else (error "unknown HIR node" node))))

    (define (lower-reference node environment builder next)
      (let* ((definition (hir:name-definition node))
             (slot (storage definition environment builder))
             (read (if (and (not (eq? (car slot) 'global))
                            (memq definition (builder-boxed builder)))
                       (emit! builder 'indirect '() next (hir:name-loc node)) next)))
        (emit! builder (case (car slot)
                         ((local) 'refer-local) ((free) 'refer-free) ((global) 'refer-global))
               (list (cdr slot)) read (hir:name-loc node))))

    (define (lower-store definition value environment builder next loc)
      (let* ((slot (storage definition environment builder))
             (store (emit! builder (case (car slot)
                                     ((local) (if (memq definition (builder-boxed builder))
                                                  'set-local 'init-local))
                                     ((free) 'set-free) ((global) 'set-global))
                           (list (cdr slot)) next loc)))
        (lower value environment builder store #f)))

    (define (lower-lambda procedure environment builder next)
      (let* ((locals (lambda-locals procedure))
             (free (free-definitions procedure (builder-globals builder)))
             (return (emit! builder 'return '() #f (hir:lambda-loc procedure)))
             (body (lower (hir:lambda-body procedure) (storage-environment locals free)
                          builder return #t))
             (entry (lower-boxes locals builder body (hir:lambda-loc procedure)))
             (close (emit! builder 'close
                           (list (define-code! builder "lambda" entry) (length (hir:lambda-parameters procedure))
                                 (if (hir:lambda-opt-rest-parameter procedure) 1 0)
                                 (length locals) (length free)) next (hir:lambda-loc procedure))))
        (lower-captures free environment builder close (hir:lambda-loc procedure))))

    (define (lower-captures free environment builder next loc)
      (if (null? free) next
          (let* ((rest (lower-captures (cdr free) environment builder next loc))
                 (push (emit! builder 'argument '() rest loc))
                 (slot (storage (car free) environment builder)))
            (emit! builder (case (car slot)
                             ((local) 'refer-local) ((free) 'refer-free)
                             (else (error "global unnecessarily captured" (car free))))
                   (list (cdr slot)) push loc))))

    ;; A core binding is eligible only if no source initializer or set! can
    ;; replace it. Identity, not spelling, distinguishes imports from shadowing.
    (define (initialized-definitions items)
      (define (visit node)
        (append (if (hir:value-binding? node) (list (hir:value-binding-definition node)) '())
                (if (hir:lambda? node) (visit (hir:lambda-body node))
                    (apply append (map visit (children node))))))
      (apply append (map visit items)))

    (define (immutable-primitives primitives items)
      (let ((written (append (initialized-definitions items) (assigned-definitions items))))
        (let loop ((remaining primitives))
          (cond ((null? remaining) '())
                ((memq (car remaining) written) (loop (cdr remaining)))
                (else (cons (car remaining) (loop (cdr remaining))))))))

    (define (direct-primitive application builder)
      (let ((operator (hir:application-operator application)))
        (and (hir:name? operator)
             (let* ((definition (hir:name-definition operator))
                    (entry (assq (hir:value-definition-name definition) direct-primitives)))
               (and (memq definition (builder-primitives builder)) entry
                    (= (length (hir:application-operands application)) (cadr entry))
                    (caddr entry))))))

    (define (lower-application application environment builder next tail?)
      (let ((primitive (direct-primitive application builder)))
        (if primitive
            (lower-direct-primitive application primitive environment builder next)
            (lower-procedure-call application environment builder next tail?))))

    (define (lower-direct-primitive application operation environment builder next)
      (let* ((definition (hir:name-definition (hir:application-operator application)))
             (index (cdr (assq definition (builder-globals builder))))
             (loc (hir:application-loc application))
             (instruction (emit! builder operation (list index) next loc)))
        (lower-arguments (hir:application-operands application) environment builder instruction loc)))

    ;; Evaluate operands left to right, then operator; leave it in the accumulator.
    (define (lower-procedure-call application environment builder next tail?)
      (let* ((operands (hir:application-operands application)) (loc (hir:application-loc application))
             (call (emit! builder 'apply (list (length operands)) #f loc))
             (transfer (if tail? (emit! builder 'shift (list (length operands)) call loc) call))
             (operator (lower (hir:application-operator application)
                              environment builder transfer #f))
             (arguments (lower-arguments operands environment builder operator loc)))
        (if tail? arguments (emit! builder 'frame (list (define-code! builder "resume" next)) arguments loc))))

    (define (lower-arguments arguments environment builder next loc)
      (if (null? arguments) next
          (let* ((rest (lower-arguments (cdr arguments) environment builder next loc))
                 (push (emit! builder 'argument '() rest loc)))
            (lower (car arguments) environment builder push #f))))

    (define (lower-conditional conditional environment builder next tail?)
      (let* ((yes (lower (hir:conditional-consequent conditional)
                         environment builder next tail?))
             (no (if (hir:conditional-opt-alternate conditional)
                     (lower (hir:conditional-opt-alternate conditional)
                            environment builder next tail?)
                     (emit! builder 'constant (list (add-constant! builder 'unspecified #f))
                            next (hir:conditional-loc conditional))))
             (test (emit! builder 'test (list yes no) #f (hir:conditional-loc conditional))))
        (lower (hir:conditional-test conditional) environment builder test #f))))


  ;; ---- Tests ----

  (cond-expand
   (snail-tests
    (export test-lower)
    (import (snail-scheme test-utils))
    (begin
      (define (test-procedure parameters items result)
        (hir:make-lambda parameters #f (hir:make-block (append items (list result)) #f) #f))
      (define (test-lowered-body node)
        (library:library-body
         (hir-library->mir-library (library:make-library #f '() '() '() (list node) #f))))
      (define (lowered-foreign-names node)
        (map mir:foreign-name
             (mir:body-foreign-descriptors (test-lowered-body node))))
      (define (expect-unboxed node)
        (let ((names (lowered-foreign-names node)))
          (expect (member "snail_rt_box" names) #f)
          (expect (member "snail_rt_cell" names) #f)))
      (define (requires-cell? node)
        (and (member "snail_rt_box" (lowered-foreign-names node)) #t))

      (define (test-immutable-bindings)
        (let* ((x (hir:make-value-definition 'x #f)) (reference (hir:make-name x #f))
               (capture (test-procedure '() '() reference)))
          (expect-unboxed (test-procedure (list x) '() reference))
          (expect-unboxed (test-procedure (list x) '() capture))
          (expect-unboxed (test-procedure '()
                                          (list (hir:make-value-binding x (hir:make-literal 1 #f) #f)) capture))))
      (define (test-assigned-bindings)
        (let* ((x (hir:make-value-definition 'x #f)) (reference (hir:make-name x #f))
               (assignment (hir:make-assignment reference (hir:make-literal 1 #f) #f)))
          (expect (requires-cell? (test-procedure (list x) (list assignment) reference)) #t)
          (expect (requires-cell? (test-procedure (list x) '()
                                                  (test-procedure '() (list assignment) reference))) #t)))
      (define (test-recursive-initialization)
        (let* ((f (hir:make-value-definition 'f #f)) (g (hir:make-value-definition 'g #f))
               (self (test-procedure '() '() (hir:make-name f #f)))
               (forward (test-procedure '() '() (hir:make-name g #f))))
          (expect (requires-cell? (test-procedure '() (list (hir:make-value-binding f self #f))
                                                  (hir:make-name f #f))) #t)
          (expect (requires-cell?
                   (test-procedure '() (list (hir:make-value-binding f forward #f)
                                             (hir:make-value-binding g (hir:make-literal 1 #f) #f))
                                   (hir:make-name f #f))) #t)))
      (define (test-resume-bodies)
        (let* ((f (hir:make-value-definition 'f #f))
               (call (hir:make-application (hir:make-name f #f) '() #f))
               (procedure (test-procedure (list f) (list call) call))
               (body (test-lowered-body procedure)))
          (expect (length (filter-resumes (mir:body-definitions body))) 1)))
      (define (filter-resumes definitions)
        (cond ((null? definitions) '())
              ((equal? (mir:code-name (mir:definition-code (car definitions))) "resume")
               (cons (car definitions) (filter-resumes (cdr definitions))))
              (else (filter-resumes (cdr definitions)))))
      (define (test-primitive-identity)
        (let* ((builtin (hir:make-value-definition '+ #f))
               (reference (hir:make-name builtin #f))
               (assigned (hir:make-assignment reference reference #f)))
          (expect (immutable-primitives (list builtin) '()) (list builtin))
          (expect (immutable-primitives (list builtin) (list (test-procedure '() '() assigned))) '())
          (expect (immutable-primitives (list builtin)
                                        (list (test-procedure '() (list (hir:make-value-binding builtin reference #f)) reference))) '())))
      (define (test-library-unit name imports datum)
        (let ((binding (hir:make-value-definition 'shared-name #f)))
          (library:make-library
           name (list (library:make-import-declaration imports '() (list name) #f))
           (list (library:make-named-binding 'shared-name binding)) '()
           (list (hir:make-value-binding binding (hir:make-literal datum #f) #f)) #f)))
      (define (test-library-diamond)
        (let* ((base (test-library-unit '(base) '() '(base)))
               (left (test-library-unit '(left) (list base) '#(11 12)))
               (right (test-library-unit '(right) (list base) "right")))
          (test-library-unit #f (list left right base) 42)))
      (define (test-imported-libraries library)
        (apply append (map library:import-declaration-libraries (library:library-imports library))))
      (define (test-entry-body body)
        (let loop ((definitions (mir:body-definitions body)))
          (if (eq? (mir:definition-code (car definitions)) (mir:body-entry body))
              (mir:definition-body (car definitions)) (loop (cdr definitions)))))
      (define (test-code-targets root)
        (let ((seen '()) (targets '()))
          (define (visit node)
            (if (not (memq node seen))
                (begin
                  (set! seen (cons node seen))
                  (if (and (mir:expression? node) (eq? (mir:expression-operation node) 'call-direct)
                           (mir:code? (car (mir:expression-operands node))))
                      (set! targets (cons (car (mir:expression-operands node)) targets)))
                  (for-each visit (mir:expression-children node)))))
          (visit root)
          targets))

      (define (test-library-graph-identity)
        (let* ((source (test-library-diamond))
               (sources (library:library-dependency-order source))
               (root (hir-library->mir-library source))
               (libraries (library:library-dependency-order root))
               (base (car libraries)))
          (expect (map library:library-name libraries) '((base) (left) (right) #f))
          (expect (test-imported-libraries root) (list (cadr libraries) (caddr libraries) base))
          (expect (test-imported-libraries (cadr libraries)) (list base))
          (expect (test-imported-libraries (caddr libraries)) (list base))
          (for-each
           (lambda (before after)
             (expect (eq? before after) #f)
             (expect (eq? (library:library-exports before) (library:library-exports after)) #t)
             (expect (eq? (library:import-declaration-source (car (library:library-imports before)))
                          (library:import-declaration-source (car (library:library-imports after)))) #t))
           sources libraries)))

      (define (test-constant-datum constants index)
        (let* ((constant (list-ref constants index)) (data (mir:constant-data constant)))
          (case (mir:constant-kind constant)
            ((pair) (cons (test-constant-datum constants (car data))
                          (test-constant-datum constants (cadr data))))
            ((vector) (list->vector (map (lambda (item) (test-constant-datum constants item)) data)))
            ((nil) '())
            (else data))))

      (define (test-library-code-and-data)
        (let* ((root (hir-library->mir-library (test-library-diamond)))
               (bodies (map library:library-body (library:library-dependency-order root)))
               (constants (map mir:body-constants bodies))
               (entries (map mir:body-entry bodies)))
          (expect (map mir:body-globals bodies) '((shared-name) (shared-name) (shared-name) (shared-name)))
          (expect (map (lambda (items) (map mir:constant-kind items)) constants)
                  '((symbol nil pair) (integer integer vector) (string) (integer)))
          (expect (map (lambda (index) (test-constant-datum (apply append constants) index))
                       '(2 5 6 7))
                  '((base) #(11 12) "right" 42))
          (for-each (lambda (body next)
                      (expect (test-code-targets (test-entry-body body)) (list next)))
                    (list (car bodies) (cadr bodies) (caddr bodies)) (cdr entries))
          (for-each (lambda (body)
                      (expect (and (memq (mir:body-entry body)
                                         (map mir:definition-code (mir:body-definitions body))) #t)
                              #t)) bodies)))

      (define (test-lower)
        (run-test test-immutable-bindings)
        (run-test test-assigned-bindings)
        (run-test test-recursive-initialization)
        (run-test test-resume-bodies)
        (run-test test-primitive-identity)
        (run-test test-library-graph-identity)
        (run-test test-library-code-and-data))))))
