(import
 (scheme base)
 (scheme write)
 (snail-scheme cli)
 (snail-scheme reader)
 (snail-scheme parser)
 (snail-scheme syntax-parser))

(define (main argv)
  (let* ((args (parse-cli-args (car argv) (cdr argv)))
         (entry-point-path (cli-args-input-path args)))
    (if (null? entry-point-path)
        (error "expected an input file"))
    (let* ((reader (file->reader entry-point-path))
           (result ((s-file) reader)))
      (if (parse-result-err? result)
          (error "parse failed" (reader-filename reader) result))
      (display (parse-result-value result))
      (newline))))
