(define-library (snail-scheme test-pattern)
  (export test-pattern)
  (import (scheme base)
          (scheme read)
          (snail-scheme pattern)
          (snail-scheme test-utils))
  (begin
    (define (read-datum text)
      (read (open-input-string text)))

    ;; Exercise matching only through the public dispatcher.
    (define (dispatch-captures ellipsis literals pattern input)
      (let ((dispatch (pattern-dispatch ellipsis literals
                                        (list (cons pattern (lambda (captures) captures))))))
        (dispatch input)))

    (define (accepts-pattern? ellipsis literals pattern)
      (not (raises? (lambda ()
                      (pattern-dispatch ellipsis literals
                                        (list (cons pattern (lambda (captures) captures))))))))

    (define (check-match pattern text captures)
      (expect (dispatch-captures '... '() pattern (read-datum text))
              captures))

    (define (check-no-match pattern text)
      (expect (dispatch-captures '... '() pattern (read-datum text)) #f))

    (define (raises? thunk)
      (guard (ex ((error-object? ex) #t)) (thunk) #f))

    (define (test-pattern-parsing)
      (for-each
       (lambda (pattern) (expect (accepts-pattern? '... '() pattern) #t))
       (list '_ 'x #t #f 42 #\a "hello" #u8(0 255) '()
             '(x . y) '(head middle ... last . tail) '((x ...) ...)
             '#(x ... last) '(_ _)))
      (for-each
       (lambda (pattern) (expect (accepts-pattern? '... '() pattern) #f))
       (list '... '(... x) '(x ... ...) '(x ... y ...) '(x x)
             '(x . x) '(x (x ...)) '#(x x) '(x . ...) (lambda () #t)))
      (expect (accepts-pattern? '::: '() '(x :::)) #t)
      (expect (accepts-pattern? '::: '() '(... x)) #t)
      (expect (accepts-pattern? '... '(lit _) '(lit lit _ _)) #t)
      (expect (accepts-pattern? '... '(...) '(... ...)) #t)
      (expect (accepts-pattern? '_ '() '_) #f)
      (expect (accepts-pattern? '_ '() '(x _)) #t)
      (expect (raises? (lambda () (dispatch-captures '... '() '(x x) (read-datum "(1 2)")))) #t))

    (define (test-dispatch-arguments)
      (expect (raises? (lambda () (pattern-dispatch 1 '() '()))) #t)
      (expect (raises? (lambda () (pattern-dispatch '... '(1) '()))) #t)
      (expect (raises? (lambda () (pattern-dispatch '... 'not-a-list '()))) #t)
      (expect (raises? (lambda () (pattern-dispatch '... '() '() #f))) #t)
      (expect (raises? (lambda () (pattern-dispatch '... '() '() eq? eq?))) #t)
      (let ((dispatch (pattern-dispatch '::: '(keyword)
                                        (list (cons '(keyword x :::) (lambda (captures) captures))))))
        (expect (dispatch (read-datum "(keyword 1 2)"))
                '((x . (1 2))))
        (expect (dispatch (read-datum "(alias 1 2)")) #f)
        (expect (dispatch (read-datum "(42 1 2)")) #f)))

    (define (test-dispatch-construction)
      (for-each
       (lambda (arms)
         (expect (raises? (lambda () (pattern-dispatch '... '() arms))) #t))
       (list 42 (cons (cons '_ (lambda (_) #t)) 'improper)
             (list 42) (list '()) (list '(x))
             (list (list 'x (lambda (_) #t)))
             (list (cons '_ 42))
             (list (cons '(x x) (lambda (_) #t)))
             (list (cons '_ (lambda (_) #t))
                   (cons '(x x) (lambda (_) #t)))))
      ;; Dispatch keeps parsed patterns and callbacks independently of external pairs.
      (let* ((pair (cons 'x (lambda (captures) captures)))
             (dispatch (pattern-dispatch '... '() (list pair))))
        (set-car! pair '(x x))
        (set-cdr! pair 42)
        (expect (dispatch (read-datum "1"))
                '((x . 1)))))

    (define (test-capture-variables)
      (for-each
       (lambda (example)
         (expect (dispatch-captures '... '(literal) (car example) (read-datum (cdr example))) '()))
       (list (cons '() "()") (cons #f "#f") (cons 42 "42")
             (cons 'literal "literal") (cons '(literal literal) "(literal literal)")
             (cons '(_ ...) "(1 2)") (cons '#(literal ...) "#(literal literal)")
             (cons '(1 ...) "(1 1)")))
      (expect (map car (dispatch-captures '... '(literal) '(literal (x ...) #(y z) . rest)
                                          (read-datum "(literal (1 2) #(3 4) . 5)")))
              '(x y z rest))
      (expect (map car (dispatch-captures '... '() '((x ...) ...) (read-datum "()"))) '(x))
      (expect (accepts-pattern? '... '(literal) '(x x)) #f)
      (expect (accepts-pattern? '... '(literal) '(x #(x))) #f)
      (expect (accepts-pattern? '... '(literal) '(#(x ...) . x)) #f))

    (define (test-atomic-matches)
      (check-match '_ "(anything . here)" '())
      (check-match 'x "(a . b)" '((x . (a . b))))
      (check-match #f "#f" '())
      (check-match #t "#t" '())
      (check-match 42 "42" '())
      (check-match #\a "#\\a" '())
      (check-match "hello" "\"hello\"" '())
      (check-match #u8() "#u8()" '())
      (check-match #u8(0 255) "#u8(0 #xff)" '())
      (check-match 'x "#u8(1 2)" '((x . #u8(1 2))))
      (check-no-match #f "#t")
      (check-no-match 42 "43")
      (check-no-match "hello" "hello")
      (check-no-match #u8(1) "#u8(2)")
      (check-no-match #u8() "()")
      (expect (dispatch-captures '... '(define) '(define name value)
                                 (read-datum "(define answer 42)"))
              '((name . answer) (value . 42)))
      (expect (dispatch-captures '... '(define) '(define name value)
                                 (read-datum "(other answer 42)")) #f)
      (expect (dispatch-captures '... '(_) '_ (read-datum "x")) #f)
      (expect (dispatch-captures '... '(_) '_ (read-datum "_")) '()))

    (define (test-list-matches)
      (check-match '() "()" '())
      (check-match '(x y) "(1 2)" '((x . 1) (y . 2)))
      (check-match '(x (y z)) "(1 (2 3))" '((x . 1) (y . 2) (z . 3)))
      (check-match '(x . rest) "(1 2 3)" '((x . 1) (rest . (2 3))))
      (check-match '(x . rest) "(1 . 2)" '((x . 1) (rest . 2)))
      (check-match '(x . rest) "(1)" '((x . 1) (rest . ())))
      (check-match '(x y) "(1 . (2))" '((x . 1) (y . 2)))
      (check-match '(x y . rest) "(1 . (2 . 3))" '((x . 1) (y . 2) (rest . 3)))
      (check-match '(x . rest) "(1 . #(2))" '((x . 1) (rest . #(2))))
      (check-no-match '(x) "()")
      (check-no-match '(x) "(1 2)")
      (check-no-match '(x y) "(1 . 2)")
      (check-no-match '(x) "1")
      (check-no-match '() "#()"))

    (define (test-repeated-matches)
      (check-match '(x ...) "()" '((x . ())))
      (check-match '(x ...) "(1 2 3)" '((x . (1 2 3))))
      (check-match '(head middle ... last) "(1 2)" '((head . 1) (middle . ()) (last . 2)))
      (check-match '(head middle ... last) "(1 2 3 4)" '((head . 1) (middle . (2 3)) (last . 4)))
      (check-match '(x ... first last) "(1 2)" '((x . ()) (first . 1) (last . 2)))
      (check-match '(x ... first last) "(1 2 3 4)" '((x . (1 2)) (first . 3) (last . 4)))
      (check-match '(x ... first last . tail) "(1 . (2 . 3))"
                   '((x . ()) (first . 1) (last . 2) (tail . 3)))
      (check-match '((name value) ...) "((a 1) (b 2))" '((name . (a b)) (value . (1 2))))
      (check-match '((name value) ...) "()" '((name . ()) (value . ())))
      (check-match '((x ...) ...) "(() (a b) ())" '((x . (() (a b) ()))))
      (check-match '((x ...) ...) "()" '((x . ())))
      (check-match '(((x ...) ...) ...) "((() (a)) () ((b c)))" '((x . ((() (a)) () ((b c))))))
      (check-match '((name value ...) ...) "((a) (b 1 2))" '((name . (a b)) (value . (() (1 2)))))
      (check-match '(_ ...) "(1 2 3)" '())
      (check-match '(1 ... last) "(1 1 2)" '((last . 2)))
      (check-match '(x ... . tail) "(1 2)" '((x . (1 2)) (tail . ())))
      (check-match '(x ... . tail) "(1 . (2 . 3))" '((x . (1 2)) (tail . 3)))
      (check-match '(x ... . tail) "()" '((x . ()) (tail . ())))
      (check-match '(head x ... . tail) "(1 . 2)" '((head . 1) (x . ()) (tail . 2)))
      (check-match '(head x ... last . tail) "(1 2 3 . 4)"
                   '((head . 1) (x . (2)) (last . 3) (tail . 4)))
      (check-match '(head x ... first last . tail) "(1 . (2 3 . (4 5 . 6)))"
                   '((head . 1) (x . (2 3)) (first . 4) (last . 5) (tail . 6)))
      ;; The constant #f is distinct from an absent repeated item or tail pattern.
      (check-match '(#f ...) "()" '())
      (check-match '(#f ... last . #f) "(#f #f 3 . #f)" '((last . 3)))
      (check-no-match '(#f ... last . #f) "(#f 3)")
      (check-no-match '(head x ... last) "(1)")
      (check-no-match '(x ... first last) "(1)")
      (check-no-match '(x ...) "(1 . 2)")
      (check-no-match '((x y) ...) "((1 2) (3))")
      (check-no-match '(1 ... last) "(1 2 3)")
      (check-no-match '(x ... . _) "42")
      (check-no-match '(x ... . _) "#()")
      ;; A dotted tail cannot take an arbitrary proper suffix after repetition.
      (check-no-match '(x ... . 2) "(1 2)")
      (check-no-match '(1 ... . tail) "(1 2)")
      (expect (dispatch-captures '::: '() '(x ::: last) (read-datum "(1 2 3)"))
              '((x . (1 2)) (last . 3)))
      (expect (dispatch-captures '... '(...) '(x ... y) (read-datum "(1 ... 2)"))
              '((x . 1) (y . 2)))
      (expect (dispatch-captures '::: '() '(... x :::) (read-datum "(1 2 3)"))
              '((... . 1) (x . (2 3)))))

    (define (test-vector-matches)
      (check-match '#() "#()" '())
      (check-match '#(x y) "#(1 2)" '((x . 1) (y . 2)))
      (check-match '#(x ... last) "#(1 2 3)" '((x . (1 2)) (last . 3)))
      (check-match '#(head x ... first last) "#(1 2 3)"
                   '((head . 1) (x . ()) (first . 2) (last . 3)))
      (check-match '#(head #(x ...) ... first last) "#(1 #(2 3) #() 4 5)"
                   '((head . 1) (x . ((2 3) ())) (first . 4) (last . 5)))
      (check-match '#(x ...) "#()" '((x . ())))
      (check-match '#(#f ...) "#()" '())
      (check-match '#(#f ...) "#(#f #f)" '())
      (check-match '(#(x ...) ...) "(#() #(1 2))" '((x . (() (1 2)))))
      (check-no-match '#(x) "(1)")
      (check-no-match '#(head x ... first last) "#(1 2)")
      (check-no-match '#(x y) "#(1 2 3)")
      (check-no-match '#(1 ... last) "#(1 2 3)")
      (check-no-match '#(#f ...) "#(#f #t)")
      (check-no-match '(x) "#(1)")
      (check-no-match '#(x) "#u8(1)")
      (check-no-match #u8(1) "#(1)"))

    (define (test-flattened-captures)
      ;; Keep outer captures in pattern order while grouping multiple variables
      ;; across repeated vectors and retaining nested empty repetition layers.
      (check-match '(head #(tag (x ...) y) ... last . tail)
                   "(0 #(1 () 2) #(3 (4 5) 6) 7 . 8)"
                   '((head . 0) (tag . (1 3)) (x . (() (4 5)))
                     (y . (2 6)) (last . 7) (tail . 8)))
      (check-match '(head #(tag (x ...) y) ... last . tail)
                   "(0 7 . 8)"
                   '((head . 0) (tag . ()) (x . ()) (y . ()) (last . 7) (tail . 8)))
      (check-match '#((name x ... last) ...) "#((a 1) (b 2 3 4))"
                   '((name . (a b)) (x . (() (2 3))) (last . (1 4)))))

    ;; This test-owned record has no meaning to the pattern library.
    (define-record-type <opaque-value>
      (make-opaque-value payload)
      opaque-value?
      (payload opaque-value-payload))

    (define (test-capture-identity)
      (let* ((first (make-opaque-value 'first))
             (second (make-opaque-value 'second))
             (input (vector first second))
             (whole (dispatch-captures '... '() 'whole input))
             (captures (dispatch-captures '... '() '#(x ...) input)))
        (expect (eq? (cdr (assq 'whole whole)) input) #t)
        (expect (eq? (car (cdr (assq 'x captures))) first) #t)
        (expect (eq? (cadr (cdr (assq 'x captures))) second) #t)
        (expect (dispatch-captures '... '(first) 'first first) #f)
        (expect (dispatch-captures '... '() '_ first) '()))
      (let* ((input (list (list 'a) (vector 'b)))
             (captures (dispatch-captures '... '() '(x y) input))
             (repeated (dispatch-captures '... '() '(x ...) input))
             (tail (dispatch-captures '... '() '(x . tail) input)))
        (expect (map car captures) '(x y))
        (expect (eq? (cdr (assq 'x captures)) (car input)) #t)
        (expect (eq? (cdr (assq 'y captures)) (cadr input)) #t)
        (expect (eq? (car (cdr (assq 'x repeated))) (car input)) #t)
        (expect (eq? (cadr (cdr (assq 'x repeated))) (cadr input)) #t)
        (expect (eq? (cdr (assq 'tail tail)) (cdr input)) #t))
      (let* ((tail (make-opaque-value 'tail))
             (input (cons 'a tail))
             (captures (dispatch-captures '... '() '(x . tail) input))
             (repeated (dispatch-captures '... '() '(x ... . tail) input)))
        (expect (eq? (cdr (assq 'tail captures)) tail) #t)
        (expect (eq? (cdr (assq 'tail repeated)) tail) #t))
      (let* ((tail (vector 'c))
             (input (cons 'a (cons 'b tail)))
             (captures (dispatch-captures '... '() '(head x ... . tail) input)))
        (expect (map car captures) '(head x tail))
        (expect (cdr (assq 'x captures)) '(b))
        (expect (eq? (cdr (assq 'tail captures)) tail) #t))
      (expect (dispatch-captures '... '() 'x #f) '((x . #f)))
      (expect (dispatch-captures '... '() 'x '()) '((x . ())))
      (expect (dispatch-captures '... '() '(x ...) '()) '((x . ()))))

    (define (test-pattern-dispatch)
      (let* ((called '())
             (dispatch
              (pattern-dispatch '... '(define import)
                                (list (cons '(import name) (lambda (_) (error "unmatched callback invoked")))
                                      (cons '(define name value)
                                            (lambda (captures)
                                              (expect captures '((name . x) (value . 1)))
                                              (set! called (cons 'declined called))
                                              #f))
                                      (cons '(define name value)
                                            (lambda (captures)
                                              (expect captures '((name . x) (value . 1)))
                                              (set! called (cons 'accepted called))
                                              'accepted))
                                      (cons '_ (lambda (_) (error "unexpected fallback"))))))
             (result (dispatch (read-datum "(define x 1)"))))
        (expect result 'accepted)
        (expect (reverse called) '(declined accepted)))
      (let* ((called '())
             (dispatch
              (pattern-dispatch '... '()
                                (list (cons '_ (lambda (_)
                                                 (set! called (cons 'first called))
                                                 #f))
                                      (cons '(x) (lambda (_)
                                                   (set! called (cons 'second called))
                                                   #f))
                                      (cons '(2) (lambda (_) (error "unmatched callback invoked")))))))
        (expect (dispatch (read-datum "(1)")) #f)
        (expect (reverse called) '(first second)))
      ;; Scheme's other values are truthy, including the empty capture alist.
      (for-each
       (lambda (value)
         (let ((dispatch (pattern-dispatch '... '()
                                           (list (cons '_ (lambda (_) value))
                                                 (cons '_ (lambda (_) (error "unexpected fallback")))))))
           (expect (dispatch (read-datum "1")) value)))
       (list #t '() 0 ""))
      (let ((dispatch (pattern-dispatch '... '()
                                        (list (cons '(1 x) (lambda (_) 'wrong))
                                              (cons '(x y) (lambda (captures) captures))))))
        (expect (dispatch (read-datum "(2 3)"))
                '((x . 2) (y . 3))))
      (let ((dispatch (pattern-dispatch '... '()
                                        (list (cons #f (lambda (captures)
                                                         (expect captures '())
                                                         '()))))))
        (expect (dispatch (read-datum "#f")) '())
        (expect (dispatch (read-datum "#t")) #f))
      (expect ((pattern-dispatch '... '() '()) (read-datum "x")) #f)
      (expect (raises? (lambda ()
                         ((pattern-dispatch '... '() (list (cons '_ (lambda (_) (error "callback failed")))
                                                           (cons '_ (lambda (_) #t))))
                          (read-datum "x")))) #t))

    (define (test-pattern)
      (run-test test-pattern-parsing)
      (run-test test-dispatch-arguments)
      (run-test test-dispatch-construction)
      (run-test test-capture-variables)
      (run-test test-atomic-matches)
      (run-test test-list-matches)
      (run-test test-repeated-matches)
      (run-test test-vector-matches)
      (run-test test-flattened-captures)
      (run-test test-capture-identity)
      (run-test test-pattern-dispatch))))
