(define-library (snail-scheme test-llvmlite)
  (export test-llvmlite llvmlite-fixture)
  (import (scheme base) (prefix (snail-scheme llvmlite) ir:)
          (snail-scheme test-utils))
  (begin
    (define (raises? thunk)
      (guard (exception ((error-object? exception) #t)) (thunk) #f))

    (define (module-text module)
      (let ((port (open-output-string))) (ir:write-module module port) (get-output-string port)))

    (define (word value) (ir:integer ir:i32 value))

    ;; The block and value references precede every definition, including the
    ;; phi's backedge values. This builds a cyclic CFG without mutating a node.
    (define (sum-definition function)
      (let* ((entry (ir:block function "entry")) (loop (ir:block function "loop"))
             (work (ir:block function "work")) (done (ir:block function "done"))
             (index (ir:local function ir:i32 "index")) (sum (ir:local function ir:i32 "sum"))
             (next (ir:local function ir:i32 "next")) (total (ir:local function ir:i32 "total"))
             (more (ir:local function ir:i1 "more")))
        (ir:define-function
         function 'internal '(alwaysinline)
         (list (ir:block-body entry '() (ir:br loop))
               (ir:block-body loop
                              (list (ir:phi index (list (cons (word 10) entry) (cons next work)))
                                    (ir:phi sum (list (cons (word 0) entry) (cons total work)))
                                    (ir:icmp more 'sgt index (word 0))) (ir:cbr more work done))
               (ir:block-body work (list (ir:binop total 'add sum index)
                                         (ir:binop next 'sub index (word 1))) (ir:br loop))
               (ir:block-body done '() (ir:ret sum))))))

    (define (count-definition name value)
      (let* ((function (ir:function name ir:i32 '())) (entry (ir:block function "entry")))
        (ir:define-function function 'external '() (list (ir:block-body entry '() (ir:ret (word value)))))))

    (define (fixture-program sum-function array halt invalid)
      (let* ((function (ir:function "snail_program" ir:void (list (cons ir:ptr "vm"))))
             (vm (ir:parameter function 0)) (entry (ir:block function "entry"))
             (pass (ir:block function "pass")) (fail (ir:block function "fail"))
             (sum (ir:local function ir:i32 "sum")) (offset (ir:local function ir:i32 "offset"))
             (answer (ir:local function ir:i32 "answer")))
        (ir:define-function
         function 'external '()
         (list (ir:block-body entry
                              (list (ir:call sum sum-function '()) (ir:load offset array)
                                    (ir:binop answer 'add sum offset))
                              (ir:switch answer fail (list (cons (word 62) pass))))
               (ir:block-body pass (list (ir:call #f halt (list vm))) (ir:ret #f))
               (ir:block-body fail (list (ir:call #f invalid (list vm answer))) (ir:ret #f))))))

    (define (llvmlite-fixture)
      (let* ((sum (ir:function "sum λ" ir:i32 '()))
             (array (ir:global-array "offset" ir:i32 (list (word 7) (word 9)) 4))
             (halt (ir:function "snail_halt" ir:void (list (cons ir:ptr "vm"))))
             (invalid (ir:function "snail_invalid_pc" ir:void
                                   (list (cons ir:ptr "vm") (cons ir:i32 "pc")))))
        (ir:module (list (count-definition "snail_program_abi" 1)
                         (count-definition "snail_global_count" 0)
                         (count-definition "snail_constant_count" 0)
                         (ir:declare halt) (ir:declare invalid)
                         (ir:global-bytes "bytes" '(0 34 92 255))
                         (ir:global-bytes "empty" '()) array
                         (sum-definition sum) (fixture-program sum array halt invalid)))))

    (define (test-immutable-construction)
      (let* ((module (llvmlite-fixture)) (first (module-text module)))
        (expect (module-text (llvmlite-fixture)) first)
        (expect (module-text module) first))
      (expect (ir:type=? (ir:array-type (ir:int-type 8) 4) (ir:array-type ir:i8 4)) #t)
      (expect (ir:type=? ir:i32 ir:i64) #f)
      (expect (ir:utf8-bytes "λ😀") '(206 187 240 159 152 128)))

    (define (test-global-bytes)
      (expect (module-text (ir:module (list (ir:global-bytes "bytes" '(0 34 92 255)))))
              "@bytes = private constant [4 x i8] c\"\\00\\22\\5C\\FF\", align 1\n")
      (expect (module-text (ir:module (list (ir:global-bytes "empty" '()))))
              "@empty = private constant [0 x i8] c\"\", align 1\n"))

    (define (test-indexed-names)
      (let ((name (ir:indexed-name "g" 12)))
        (expect (module-text (ir:module (list (ir:global-bytes name '(42)))))
                (module-text (ir:module (list (ir:global-bytes "g12" '(42)))))))
      (for-each (lambda (arguments)
                  (expect (raises? (lambda () (apply ir:indexed-name arguments))) #t))
                '(("" 1) ("1b" 2) ("bad name" 0) ("b" -1) ("b" 1.0))))

    (define (test-invalid-instructions)
      (let* ((function (ir:function "f" ir:i32 '())) (entry (ir:block function "entry"))
             (value (ir:local function ir:i32 "value")) (condition (ir:local function ir:i1 "test"))
             (call (ir:call value function '())) (phi (ir:phi value (list (cons (word 0) entry)))))
        (for-each (lambda (thunk) (expect (raises? thunk) #t))
                  (list (lambda () (ir:cbr value entry entry))
                        (lambda () (ir:call value function (list (word 1))))
                        (lambda () (ir:icmp condition 'eq (word 1) ir:null-pointer))
                        (lambda () (ir:block-body entry (list call phi) (ir:ret value)))
                        (lambda () (ir:block-body entry (list (ir:ret value)) (ir:ret value)))
                        (lambda () (ir:block-body entry '() call))
                        (lambda () (ir:block-body entry '() (ir:ret #f)))
                        (lambda () (ir:global-bytes "bytes" '(256)))
                        (lambda () (ir:global-bytes "" '(1)))))))

    (define (test-reference-scopes)
      (let* ((first (ir:function "f" ir:i32 '())) (second (ir:function "g" ir:i32 '()))
             (entry (ir:block first "entry")) (foreign (ir:block second "entry"))
             (value (ir:local second ir:i32 "value")))
        (expect (raises? (lambda () (ir:block-body entry '() (ir:br foreign)))) #t)
        (expect (raises? (lambda () (ir:block-body entry '() (ir:ret value)))) #t)
        (expect (raises? (lambda ()
                           (ir:define-function second 'external '()
                                               (list (ir:block-body entry '() (ir:ret (word 1))))))) #t)))

    (define (test-llvmlite)
      (run-test test-immutable-construction)
      (run-test test-global-bytes)
      (run-test test-indexed-names)
      (run-test test-invalid-instructions)
      (run-test test-reference-scopes))))
