(define-library (snail-scheme test-react)
  (export test-react)
  (import (scheme base) (snail-scheme react) (snail-scheme test-utils))
  (begin
    (define (test-element-construction)
      (let* ((calls 0)
             (component (lambda (props children) (set! calls (+ calls 1)) children))
             (props '((title . "Example")))
             (element (create-element component props "body")))
        (expect (element? element) #t)
        (expect (eq? (element-type element) component) #t)
        (expect (element-props element) props)
        (expect (element-children element) '("body"))
        (expect calls 0)
        (expect (render element) '("body"))
        (expect (render element) '("body"))
        (expect calls 2)))

    (define (test-component-composition)
      (define (greeting props children)
        (create-element 'paragraph '() "Hello, " (cdr (assq 'name props)) children))
      (define (page props children)
        (create-element 'document props
                        (create-element greeting '((name . "Scheme")) "!") children))
      (expect (render (create-element page '((title . "Guide"))
                                      (create-element 'emphasis '() "More")))
              '((document ((title . "Guide"))
                          (paragraph () "Hello, " "Scheme" "!") (emphasis () "More")))))

    (define (test-selected-children)
      (define (unused props children) (error "unused component must not run"))
      (define (choose props children) (car children))
      (expect (render (create-element choose '() "selected"
                                      (create-element unused '()) #t '("invalid" . tail)))
              '("selected")))

    (define (test-component-child-order)
      (let ((visits '()))
        (define (child props children)
          (let ((name (cdr (assq 'name props))))
            (set! visits (cons name visits))
            (create-element name '())))
        (define (reorder props children)
          (list (cadr children) (car children) (cadr children)))
        (expect (render (create-element reorder '()
                                        (create-element child '((name . a)))
                                        (create-element child '((name . b)))))
                '((b ()) (a ()) (b ())))
        (expect (reverse visits) '(b a b))))

    (define (test-fragments)
      (expect (render (list "a" (list #f '() 0 (list "" "b")) "c"))
              '("a" 0 "" "b" "c"))
      (expect (render (create-element 'list '()
                                      (map (lambda (n) (create-element 'item '() n)) '(1 2 3))))
              '((list () (item () 1) (item () 2) (item () 3))))
      (expect (render #f) '())
      (expect (render '()) '())
      (expect (render (create-element 'empty '() #f '())) '((empty ()))))

    (define (test-component-results)
      (define (return-prop props children) (cdr (assq 'result props)))
      (for-each
       (lambda (result)
         (expect (render (create-element return-prop (list (cons 'result result))))
                 (render result)))
       (list #f '() "text" 42 (list "one" (create-element 'two '())))))

    (define (test-render-order)
      (let ((visits '()))
        (define (visit props children)
          (let ((name (cdr (assq 'name props))))
            (set! visits (cons name visits))
            (create-element name '() children)))
        (define (at name . children)
          (create-element visit (list (cons 'name name)) children))
        (expect (render (list (at 'a (at 'b)) (list (at 'c) (at 'd))))
                '((a () (b ())) (c ()) (d ())))
        (expect (reverse visits) '(a b c d))))

    (define (test-host-values)
      (let* ((handler (lambda () (error "render must not call property values")))
             (props (list (cons 'activate handler) (cons 'enabled #f)))
             (node (car (render (create-element 'button props "<Save & close>" 3)))))
        (expect (car node) 'button)
        (expect (eq? (cdr (assq 'activate (cadr node))) handler) #t)
        (expect (cdr (assq 'enabled (cadr node))) #f)
        (expect (cddr node) '("<Save & close>" 3))))

    (define (test-render-errors)
      (define (fails? thunk)
        (guard (condition ((error-object? condition) #t)) (thunk) #f))
      (for-each
       (lambda (thunk) (expect (fails? thunk) #t))
       (list (lambda () (create-element 12 '()))
             (lambda () (create-element 'p #f))
             (lambda () (create-element 'p '(title)))
             (lambda () (create-element 'p '((1 . "title"))))
             (lambda () (create-element 'p '((id . 1) (id . 2))))
             (lambda () (create-element 'p '((id . 1) . tail)))
             (lambda () (render #t))
             (lambda () (render 'unbound-text))
             (lambda () (render '("text" . tail)))
             (lambda () (render (create-element (lambda (props children) #t) '()))))))

    (define (test-component-error-propagation)
      (let ((failure (list 'component-failure)))
        (expect (guard (condition (else (eq? condition failure)))
                  (render (create-element (lambda (props children) (raise failure)) '()))
                  #f)
                #t)))

    (define (test-improper-fragment-order)
      (let ((visits '()))
        (define (visit props children)
          (set! visits (cons (cdr (assq 'name props)) visits))
          #f)
        (expect (guard (condition ((error-object? condition) #t))
                  (render (list (create-element visit '((name . first)))
                                (cons (create-element visit '((name . invalid-prefix))) 'tail)))
                  #f)
                #t)
        (expect visits '(first))))

    (define (test-react)
      (run-test test-element-construction)
      (run-test test-component-composition)
      (run-test test-selected-children)
      (run-test test-component-child-order)
      (run-test test-fragments)
      (run-test test-component-results)
      (run-test test-render-order)
      (run-test test-host-values)
      (run-test test-render-errors)
      (run-test test-component-error-propagation)
      (run-test test-improper-fragment-order))))
