(define-library (snail-scheme test-ui)
  (export test-ui)
  (import (scheme base) (snail-scheme react) (snail-scheme ui)
          (snail-scheme html) (snail-scheme test-utils))
  (begin
    (define (markup description)
      (let-values (((text actions) (render-html description))) text))

    (define (fails? thunk)
      (guard (condition ((error-object? condition) #t)) (thunk) #f))

    (define (test-reducer)
      (let* ((views 0)
             (view (lambda (model) (set! views (+ views 1)) (element 'output '() model)))
             (app (application 4 (lambda (message model) (+ model message)) view))
             (next (dispatch app 3)))
        (expect (application? next) #t)
        (expect (application-model app) 4)
        (expect (application-model next) 7)
        (expect views 0)
        (expect (markup (application-view next)) "<output>7</output>")
        (expect views 1)))

    (define (test-reducer-errors)
      (let* ((failure (list 'reducer-failure))
             (app (application 'original (lambda (message model) (raise failure)) values)))
        (expect (guard (condition (else (eq? condition failure))) (dispatch app 'fail) #f) #t)
        (expect (application-model app) 'original)
        (expect (application-view app) 'original)))

    (define (test-html-escaping)
      (expect (markup (element 'p '((title . "\"<&'>") (hidden . #f) (tabindex . 0))
                               "<&>\"'" #\& 42))
              "<p title=\"&quot;&lt;&amp;&#39;&gt;\" tabindex=\"0\">&lt;&amp;&gt;&quot;&#39;&amp;42</p>")
      (expect (markup (element 'input '((disabled . #t) (value . "yes"))))
              "<input disabled value=\"yes\">")
      (expect (markup (fragment "a" (fragment) (element 'br '()) "b")) "a<br>b"))

    (define (test-static-buttons)
      (let-values (((text actions) (render-html (button #f "Try <this>"))))
        (expect text "<button type=\"button\" disabled>Try &lt;this&gt;</button>")
        (expect actions '())))

    (define (test-live-buttons)
      (let-values (((text actions) (render-html (fragment (button #f "First")
                                                          (button '(adjust 1) "Second")) "/event/8/")))
        (expect actions '(("/event/8/0" . #f) ("/event/8/1" . (adjust 1))))
        (expect text (string-append
                      "<form method=\"post\" action=\"/event/8/0\"><button type=\"submit\">First</button></form>"
                      "<form method=\"post\" action=\"/event/8/1\"><button type=\"submit\">Second</button></form>"))))

    (define (test-rendered-action-order)
      (let ((calls 0))
        (define (choices data children)
          (set! calls (+ calls 1)) (fragment (button 'a "A") (button 'b "B")))
        (let-values (((text actions) (render-html (element choices #f) "/events/")))
          (expect calls 1)
          (expect (map cdr actions) '(a b)))))

    (define (test-html-errors)
      (for-each
       (lambda (description) (expect (fails? (lambda () (markup description))) #t))
       (list #f #t '(literal list) 'bare-symbol (element 42 '())
             (element 'Bad '()) (element (string->symbol "p><img") '())
             (element 'p #f) (element 'p '(id)) (element 'p '((id . 1) (id . 2)))
             (element 'p '((id . ()) )) (element 'p '((id . 1) . tail))
             (element 'p '((9 . "bad"))) (element 'p '((title . #\x)))
             (element 'img '() "child") (element 'script '() "alert(1)")
             (element 'style '() "p{}") (element 'plaintext '() "text")
             (element 'form '() (element 'form '()))))
      (expect (fails? (lambda () (button 'message (element 'b '() "label")))) #t)
      (expect (fails? (lambda () (render-html (element 'form '() (button 'go "Go")) "/"))) #t)
      (expect (fails? (lambda ()
                        (render-html (element 'form '()
                                              (element (lambda (data children) (button 'go "Go")) #f))
                                     "/"))) #t))

    (define (test-ui)
      (run-test test-reducer)
      (run-test test-reducer-errors)
      (run-test test-html-escaping)
      (run-test test-static-buttons)
      (run-test test-live-buttons)
      (run-test test-rendered-action-order)
      (run-test test-html-errors))))
