(define-library (snail-scheme test-react)
  (export test-react)
  (import (scheme base) (snail-scheme react) (snail-scheme test-utils))
  (begin
    ;; A test-only presentation of element records. Lists in payloads and leaf
    ;; positions remain data; only element children are traversed.
    (define (tree->datum tree)
      (if (element? tree)
          (cons (element-type tree)
                (cons (element-data tree) (map tree->datum (element-children tree))))
          tree))

    (define (resolved-data description)
      (map tree->datum (resolve description)))

    (define (test-element-construction)
      (let* ((calls 0)
             (component (lambda (data children)
                          (set! calls (+ calls 1)) (apply fragment children)))
             (data (vector 'arbitrary 'payload))
             (description (element component data "body")))
        (expect (element? description) #t)
        (expect (eq? (element-type description) component) #t)
        (expect (eq? (element-data description) data) #t)
        (expect (element-children description) '("body"))
        (expect calls 0)
        (expect (resolve description) '("body"))
        (expect (resolve description) '("body"))
        (expect calls 2)))

    (define (test-component-composition)
      (define (greeting name children)
        (element 'paragraph #f "Hello, " name (apply fragment children)))
      (define (page title children)
        (element 'document title (element greeting "Scheme" "!") (apply fragment children)))
      (expect (resolved-data (element page "Guide" (element 'emphasis #f "More")))
              '((document "Guide" (paragraph #f "Hello, " "Scheme" "!") (emphasis #f "More")))))

    (define (test-selected-children)
      (define (unused data children) (error "unused component must not run"))
      (define (choose data children) (car children))
      (expect (resolve (element choose #f "selected" (element unused #f))) '("selected")))

    (define (test-component-child-order)
      (let ((visits '()))
        (define (child name children)
          (set! visits (cons name visits)) (element name #f))
        (define (reorder data children)
          (fragment (cadr children) (car children) (cadr children)))
        (expect (resolved-data (element reorder #f (element child 'a) (element child 'b)))
                '((b #f) (a #f) (b #f)))
        (expect (reverse visits) '(b a b))))

    (define (test-fragments)
      (expect (resolve (fragment "a" (fragment (fragment) #f '() 0 "" "b") "c"))
              '("a" #f () 0 "" "b" "c"))
      (expect (resolved-data
               (element 'list #f (apply fragment (map (lambda (n) (element 'item #f n)) '(1 2 3)))))
              '((list #f (item #f 1) (item #f 2) (item #f 3))))
      (expect (resolve (fragment)) '())
      (expect (fragment? (fragment 1 2)) #t)
      (expect (fragment-children (fragment 1 2)) '(1 2)))

    (define (test-opaque-values)
      (let* ((handler (lambda () (error "opaque procedure must not run")))
             (values (list #f #t '() '(a . b) 'symbol (vector 1 2) handler)))
        (for-each (lambda (value) (expect (eq? (car (resolve value)) value) #t)) values)
        (let ((node (car (resolve (element 42 handler values)))))
          (expect (element-type node) 42)
          (expect (eq? (element-data node) handler) #t)
          (expect (eq? (car (element-children node)) values) #t))))

    (define (test-component-results)
      (define (return-data data children) data)
      (for-each
       (lambda (result)
         (expect (resolved-data (element return-data result)) (resolved-data result)))
       (list #f '() '(one two) 42 (fragment "one" (element 'two #f)))))

    (define (test-resolve-order)
      (let ((visits '()))
        (define (visit name children)
          (set! visits (cons name visits)) (apply element name #f children))
        (define (at name . children) (apply element visit name children))
        (expect (resolved-data (fragment (at 'a (at 'b)) (fragment (at 'c) (at 'd))))
                '((a #f (b #f)) (c #f) (d #f)))
        (expect (reverse visits) '(a b c d))))

    (define (test-resolved-elements)
      (let ((calls 0))
        (define (component data children)
          (set! calls (+ calls 1)) (element 'result data '(literal list)))
        (let ((forest (resolve (element component #f))))
          (expect (map tree->datum (resolve (apply fragment forest)))
                  (map tree->datum forest))
          (expect calls 1))))

    (define (test-component-error-propagation)
      (let ((failure (list 'component-failure)))
        (expect (guard (condition (else (eq? condition failure)))
                  (resolve (element (lambda (data children) (raise failure)) #f)) #f)
                #t)))

    (define (test-react)
      (run-test test-element-construction)
      (run-test test-component-composition)
      (run-test test-selected-children)
      (run-test test-component-child-order)
      (run-test test-fragments)
      (run-test test-opaque-values)
      (run-test test-component-results)
      (run-test test-resolve-order)
      (run-test test-resolved-elements)
      (run-test test-component-error-propagation))))
