(define-library (snail-scheme test-syntax)
  (export
   test-syntax)

  (import
   (scheme base)
   (snail-scheme source)
   (snail-scheme reader)
   (only (snail-scheme parser) pmap)
   (snail-scheme syntax)
   (rename (snail-scheme test-utils) (check-ok check-parser-ok)))

  (begin
    ;; Compare syntax structurally, including source locations at every node.
    (define (syntax-value value)
      (cond
       ((atom-syntax? value)
        (list 'atom (atom-syntax-value value) (syntax-value (syntax-loc value))))
       ((list-syntax? value)
        (list 'list
              (syntax-value (list-syntax-elements value))
              (syntax-value (list-syntax-improper-tail value))
              (syntax-value (syntax-loc value))))
       ((loc? value)
        (list (loc-filename value) (loc-line value) (loc-column value)))
       ((pair? value) (cons (syntax-value (car value)) (syntax-value (cdr value))))
       (else value)))

    (define (atom value line column)
      (make-atom-syntax value (at line column)))

    (define (check-ok parser text value . remainder)
      (apply check-parser-ok (pmap parser syntax-value) text (syntax-value value) remainder))

    (define (test-whitespace)
      (check-ok (whitespace) "" '())
      (check-ok (whitespace) " \t\n\ra" '() "a")
      (check-ok (whitespace) "a" '() "a")
      (check-ok (whitespace) " ; comment" '() "; comment")
      (check-ok (whitespace) "#| comment |#" '() "#| comment |#")
      (check-fail (whitespace-char) "a"))

    (define (test-intertoken-space)
      (check-ok (intertoken-space) "" '())
      (check-ok (intertoken-space) "x" '() "x")
      (check-ok (intertoken-space) " \t\n\rx" '() "x")
      (check-ok (intertoken-space) " ; line\n#| block |# #; ignored \tx" '() "x"))

    (define (test-comments)
      (check-ok (line-comment) "; comment\nx" '() "\nx")
      (check-ok (line-comment) "; comment" '())
      (check-fail (line-comment) "x")
      (check-ok (block-comment) "#| outer #| inner |# end |#x" '() "x")
      (check-ok (block-comment) "#||#" '())
      (check-fail (block-comment) "#| unfinished" "")
      (check-ok (datum-comment) "#;(a . b)x" '() "x")
      (check-ok (datum-comment) "#;#;a b c" '() " c")
      (check-fail (datum-comment) "#;" "")
      (check-ok (file) "; line\n#| block |# #; ignored " '())
      (check-ok (file) "; line\n#;#t x" (list (atom 'x 2 6)))
      (check-ok (list-expr) "(;line\n a #;b . #|tail|# c )"
                (make-list-syntax (list (atom 'a 2 2)) (atom 'c 2 19) (at 1 1)))
      (check-fail (file) "#| unfinished")
      (check-fail (file) "#;")
      (check-fail (file) "#| outer #| unfinished |#")
      (check-ok (block-comment) "#| # #| nested |# | |#x" '() "x"))

    (define (test-token-end)
      (check-ok (token-end) ";" '() ";")
      (check-ok (token-end) "" '())
      (check-fail (token-end) "a"))

    (define (test-boolean-expr)
      (check-ok (boolean-expr) "#t" (atom #t 1 1))
      (check-ok (boolean-expr) "#FALSE" (atom #f 1 1))
      (check-ok (boolean-expr) "#True)" (atom #t 1 1) ")")
      (check-fail (boolean-expr) "#trueish" "ish")
      (check-fail (boolean-expr) ""))

    (define (test-integers)
      (check-ok (decimal-digit) "9a" #\9 "a")
      (check-fail (decimal-digit) "a")
      (check-ok (hexadecimal-digit) "Fz" #\F "z")
      (check-fail (hexadecimal-digit) "g")
      (check-ok (decimal-integer) "123a" 123 "a")
      (check-ok (hexadecimal-integer) "aFz" 175 "z")
      (check-fail (decimal-integer) "")
      (check-fail (hexadecimal-integer) "g"))

    (define (test-number-expr)
      (for-each
       (lambda (case) (check-ok (number-expr) (car case) (atom (cadr case) 1 1)))
       '(("0" 0) ("123" 123) ("-12" -12) ("#xFF" 255)
         ("#b101" 5)
         ("#o17" 15)
         ("#d12" 12)
         ("3/4" 3/4)
         ("1.25" 1.25)
         ("2e3" 2000.0)
         ("#e1.25" 5/4)
         ("1+2i" 1+2i)
         ("#E#Xf/f" 1) ("#x#e10" 16) ("#e#d1.25" 5/4)
         ("#i#b10" 2.0) ("#D#I12" 12.0) ("#O17" 15)
         (".5" 0.5) ("1." 1.0) ("-1.25E-2" -0.0125)
         ("+i" +i) ("-i" -i) ("+2i" +2i) ("2-i" 2-i)
         ("1/2+3/4i" 1/2+3/4i) ("1e2-5e-1i" 100.0-0.5i)
         ("+inf.0" +inf.0) ("-inf.0" -inf.0) ("2@0" 2)))
      (check-ok (number-expr) "12)" (atom 12 1 1) ")")
      (check-fail (number-expr) "12abc" "abc")
      (check-fail (number-expr) "#x")
      (check-fail (number-expr) "#e1/0" "")
      (check-fail (number-expr) ""))

    (define (test-identifier-expr)
      (for-each
       (lambda (name) (check-ok (identifier-expr) name (atom (string->symbol name) 1 1)))
       '("hello?" "a.b" "+" "-" "..." "+.x" ".x" "+item" "-inf.0x" "+@x" "-.." "λ"))
      (check-ok (identifier-expr) "abc\t" (atom 'abc 1 1) "\t")
      (check-ok (identifier-expr) "abc\n" (atom 'abc 1 1) "\n")
      (check-fail (identifier-expr) "12abc")
      (check-fail (identifier-expr) "+i")
      (check-fail (identifier-expr) "abc#t" "#t")
      (check-fail (identifier-expr) ".")
      (check-fail (identifier-expr) "\"unterminated"))

    (define (test-char-expr)
      (for-each
       (lambda (case) (check-ok (char-expr) (car case) (atom (cadr case) 1 1)))
       '(("#\\a" #\a) ("#\\x" #\x) ("#\\x41" #\A)
         ("#\\alarm" #\alarm)
         ("#\\backspace" #\backspace)
         ("#\\delete" #\delete)
         ("#\\escape" #\escape)
         ("#\\newline" #\newline)
         ("#\\null" #\null)
         ("#\\return" #\return)
         ("#\\space" #\space)
         ("#\\tab" #\tab)))
      (check-ok (char-expr) "#\\))" (atom #\) 1 1) ")")
      (check-fail (char-expr) "#\\")
      (check-fail (char-expr) "#\\spacebar" "bar")
      (check-fail (char-expr) "#\\x110000" "110000")
      (check-fail (char-expr) "#\\xd800" "d800"))

    (define (test-string-expr)
      (check-ok (string-expr) "\"\"" (atom "" 1 1))
      (check-ok (string-expr) "\"hello \" " (atom "hello " 1 1) " ")
      (check-ok (string-expr) "\"\\a\\b\\t\\n\\r\\\"\\\\\""
                (atom (string #\alarm #\backspace #\tab #\newline #\return #\" #\\) 1 1))
      (check-ok (string-expr) "\"\\x41;\"" (atom "A" 1 1))
      (check-ok (string-expr-element) "\\x41;z" #\A "z")
      (check-fail (string-expr-element) "\\q")
      (check-fail (string-expr) "\"abc" "")
      (check-fail (string-expr) "\"\\q\"" "\\q\"")
      (check-fail (string-expr) "\"\\x41\"" "\\x41\"")
      (check-fail (string-expr) "\"\\xd800;\"" "\\xd800;\""))

    (define (test-list-expr)
      (check-ok (list-expr) "()" (make-list-syntax '() '() (at 1 1)))
      (check-ok (list-expr) "( \n)" (make-list-syntax '() '() (at 1 1)))
      (check-ok (list-expr) "(a 12 )"
                (make-list-syntax (list (atom 'a 1 2) (atom 12 1 4)) '() (at 1 1)))
      (check-ok (list-expr) "(a . b )"
                (make-list-syntax (list (atom 'a 1 2)) (atom 'b 1 6) (at 1 1)))
      (check-ok (list-expr) "(())"
                (make-list-syntax (list (make-list-syntax '() '() (at 1 2))) '() (at 1 1)))
      (check-ok (list-expr) "(a . ())"
                (make-list-syntax (list (atom 'a 1 2)) (make-list-syntax '() '() (at 1 6)) (at 1 1)))
      (check-fail (list-expr) "(. a)" "")
      (check-fail (list-expr) "(a .)" ".)")
      (check-fail (list-expr) "(a . b c)" "c)")
      (check-fail (list-expr) "(a" ""))

    (define (test-fenders-and-tail)
      (check-ok (left-fender) "(a" '() "a")
      (check-ok (right-fender) ")a" '() "a")
      (check-fail (left-fender) ")")
      (check-fail (right-fender) "")
      (check-ok (improper-tail) " . a" (atom 'a 1 4))
      (check-ok (improper-tail) " .a" '() " .a")
      (check-ok (improper-tail) " .)" '() " .)"))

    (define (test-quote-expr)
      (for-each
       (lambda (case)
         (let ((prefix (car case)) (name (cadr case)))
           (check-ok (quote-expr) (string-append prefix "x")
                     (make-list-syntax (list (atom name 1 1) (atom 'x 1 (+ 1 (string-length prefix))))
                                       '()
                                       (at 1 1)))))
       '(("'" quote) ("`" quasiquote) ("," unquote) (",@" unquote-splicing)))
      (check-ok (quote-expr) "'\nx"
                (make-list-syntax (list (atom 'quote 1 1) (atom 'x 2 1)) '() (at 1 1)))
      (check-ok (quote-expr) "''x"
                (make-list-syntax
                 (list (atom 'quote 1 1)
                       (make-list-syntax (list (atom 'quote 1 2) (atom 'x 1 3)) '() (at 1 2)))
                 '()
                 (at 1 1)))
      (check-fail (quote-expr) "'" "")
      (check-fail (quote-expr) ",@)" ")"))

    (define (test-expr-and-file)
      (check-ok (expr) " \n12 " (atom 12 2 1) " ")
      (check-ok (file) "" '())
      (check-ok (file) " \n\t" '())
      (check-ok (file) "abc 12\n" (list (atom 'abc 1 1) (atom 12 1 5)))
      (for-each
       (lambda (text) (check-fail (file) text))
       '("12abc" "#b102" "#o8" "#xg" "#x1.2" "1e" "1e+" "1/" "1/2/3" "3i" "#e#i1" "#x#b1" "#trueish" "abc#t" "#\\spacebar" "\"\\q\"" "\"unterminated" "(a" ")" ".")))

    (define (test-parse-file)
      (expect (parse-file (string->reader "empty.scm" "")) '())
      (expect
       (syntax-value (parse-file (string->reader "example.scm" "\n'x ")))
       (syntax-value
        (list (make-list-syntax
               (list (make-atom-syntax 'quote (make-loc "example.scm" 2 1))
                     (make-atom-syntax 'x (make-loc "example.scm" 2 2)))
               '()
               (make-loc "example.scm" 2 1)))))
      (expect
       (guard (ex ((and (error-object? ex) (equal? (error-object-message ex) "parse failed"))
                   (car (error-object-irritants ex))))
         (parse-file (string->reader "broken.scm" "(")))
       "broken.scm"))

    (define (test-syntax)
      (run-test test-whitespace)
      (run-test test-intertoken-space)
      (run-test test-comments)
      (run-test test-token-end)
      (run-test test-boolean-expr)
      (run-test test-integers)
      (run-test test-number-expr)
      (run-test test-identifier-expr)
      (run-test test-char-expr)
      (run-test test-string-expr)
      (run-test test-list-expr)
      (run-test test-fenders-and-tail)
      (run-test test-quote-expr)
      (run-test test-expr-and-file)
      (run-test test-parse-file))))
