(define-library (snail-scheme test-syntax-match)
  (export test-syntax-match)
  (import (scheme base)
          (snail-scheme reader)
          (snail-scheme parser)
          (snail-scheme source)
          (snail-scheme syntax)
          (snail-scheme syntax-parser)
          (snail-scheme syntax-pattern)
          (snail-scheme test-utils))
  (begin
    (define (read-syntax text)
      (let ((result ((s-file) (string->reader "match.scm" text))))
        (expect (parse-result-ok? result) #t)
        (car (parse-result-value result))))

    (define (capture-value value)
      (if (syntax? value) (syntax->datum value) (map capture-value value)))

    (define (capture-values captures)
      (and captures
           (map (lambda (capture)
                  (cons (car capture) (capture-value (cdr capture))))
                captures)))

    ;; Exercise matching only through the public dispatcher.
    (define (dispatch-captures ellipsis literals pattern input)
      (let ((dispatch (syntax-dispatch ellipsis literals
                                       (list (cons pattern (lambda (captures) captures))))))
        (dispatch input)))

    (define (accepts-pattern? ellipsis literals pattern)
      (not (raises? (lambda ()
                      (syntax-dispatch ellipsis literals
                                       (list (cons pattern (lambda (captures) captures))))))))

    (define (check-match pattern text captures)
      (expect (capture-values (dispatch-captures '... '() pattern (read-syntax text)))
              captures))

    (define (check-no-match pattern text)
      (expect (dispatch-captures '... '() pattern (read-syntax text)) #f))

    (define (raises? thunk)
      (guard (ex ((error-object? ex) #t)) (thunk) #f))

    (define (test-pattern-parsing)
      (for-each
       (lambda (pattern) (expect (accepts-pattern? '... '() pattern) #t))
       (list '_ 'x #t #f 42 #\a "hello" #u8(0 255) '()
             '(x . y) '(head middle ... last . tail) '((x ...) ...)
             '#(x ... last) '(_ _)))
      (for-each
       (lambda (pattern) (expect (accepts-pattern? '... '() pattern) #f))
       (list '... '(... x) '(x ... ...) '(x ... y ...) '(x x)
             '(x . x) '(x (x ...)) '#(x x) '(x . ...) (lambda () #t)))
      (expect (accepts-pattern? '::: '() '(x :::)) #t)
      (expect (accepts-pattern? '::: '() '(... x)) #t)
      (expect (accepts-pattern? '... '(lit _) '(lit lit _ _)) #t)
      (expect (accepts-pattern? '... '(...) '(... ...)) #t)
      (expect (accepts-pattern? '_ '() '_) #f)
      (expect (accepts-pattern? '_ '() '(x _)) #t)
      (expect (raises? (lambda () (dispatch-captures '... '() '(x x) (read-syntax "(1 2)")))) #t))

    (define (test-dispatch-arguments)
      (expect (raises? (lambda () (syntax-dispatch 1 '() '()))) #t)
      (expect (raises? (lambda () (syntax-dispatch '... '(1) '()))) #t)
      (expect (raises? (lambda () (syntax-dispatch '... 'not-a-list '()))) #t)
      (expect (raises? (lambda () (syntax-dispatch '... '() '() #f))) #t)
      (expect (raises? (lambda () (syntax-dispatch '... '() '() eq? eq?))) #t)
      (let ((dispatch (syntax-dispatch '::: '(keyword)
                                       (list (cons '(keyword x :::) capture-values)))))
        (expect (dispatch (read-syntax "(keyword 1 2)"))
                '((x . (1 2))))
        (expect (dispatch (read-syntax "(alias 1 2)")) #f)
        (expect (dispatch (read-syntax "(42 1 2)")) #f)))

    (define (test-dispatch-construction)
      (for-each
       (lambda (arms)
         (expect (raises? (lambda () (syntax-dispatch '... '() arms))) #t))
       (list 42 (cons (cons '_ (lambda (_) #t)) 'improper)
             (list 42) (list '()) (list '(x))
             (list (list 'x (lambda (_) #t)))
             (list (cons '_ 42))
             (list (cons '(x x) (lambda (_) #t)))
             (list (cons '_ (lambda (_) #t))
                   (cons '(x x) (lambda (_) #t)))))
      ;; Dispatch keeps parsed patterns and callbacks independently of external pairs.
      (let* ((pair (cons 'x capture-values))
             (dispatch (syntax-dispatch '... '() (list pair))))
        (set-car! pair '(x x))
        (set-cdr! pair 42)
        (expect (dispatch (read-syntax "1"))
                '((x . 1)))))

    (define (test-capture-variables)
      (for-each
       (lambda (example)
         (expect (dispatch-captures '... '(literal) (car example) (read-syntax (cdr example))) '()))
       (list (cons '() "()") (cons #f "#f") (cons 42 "42")
             (cons 'literal "literal") (cons '(literal literal) "(literal literal)")
             (cons '(_ ...) "(1 2)") (cons '#(literal ...) "#(literal literal)")
             (cons '(1 ...) "(1 1)")))
      (expect (map car (dispatch-captures '... '(literal) '(literal (x ...) #(y z) . rest)
                                          (read-syntax "(literal (1 2) #(3 4) . 5)")))
              '(x y z rest))
      (expect (map car (dispatch-captures '... '() '((x ...) ...) (read-syntax "()"))) '(x))
      (expect (accepts-pattern? '... '(literal) '(x x)) #f)
      (expect (accepts-pattern? '... '(literal) '(x #(x))) #f)
      (expect (accepts-pattern? '... '(literal) '(#(x ...) . x)) #f))

    (define (test-atomic-matches)
      (check-match '_ "(anything . here)" '())
      (check-match 'x "(a . b)" '((x . (a . b))))
      (check-match #f "#f" '())
      (check-match #t "#t" '())
      (check-match 42 "42" '())
      (check-match #\a "#\\a" '())
      (check-match "hello" "\"hello\"" '())
      (check-match #u8() "#u8()" '())
      (check-match #u8(0 255) "#u8(0 #xff)" '())
      (check-match 'x "#u8(1 2)" '((x . #u8(1 2))))
      (check-no-match #f "#t")
      (check-no-match 42 "43")
      (check-no-match "hello" "hello")
      (check-no-match #u8(1) "#u8(2)")
      (check-no-match #u8() "()")
      (expect (capture-values (dispatch-captures '... '(define) '(define name value)
                                                 (read-syntax "(define answer 42)")))
              '((name . answer) (value . 42)))
      (expect (dispatch-captures '... '(define) '(define name value)
                                 (read-syntax "(other answer 42)")) #f)
      (expect (dispatch-captures '... '(_) '_ (read-syntax "x")) #f)
      (expect (capture-values (dispatch-captures '... '(_) '_ (read-syntax "_"))) '()))

    (define (test-list-matches)
      (check-match '() "()" '())
      (check-match '(x y) "(1 2)" '((x . 1) (y . 2)))
      (check-match '(x (y z)) "[1 {2 3}]" '((x . 1) (y . 2) (z . 3)))
      (check-match '(x . rest) "(1 2 3)" '((x . 1) (rest . (2 3))))
      (check-match '(x . rest) "(1 . 2)" '((x . 1) (rest . 2)))
      (check-match '(x . rest) "(1)" '((x . 1) (rest . ())))
      (check-match '(x y) "(1 . (2))" '((x . 1) (y . 2)))
      (check-match '(x y . rest) "(1 . (2 . 3))" '((x . 1) (y . 2) (rest . 3)))
      (check-match '(x . rest) "(1 . #(2))" '((x . 1) (rest . #(2))))
      (check-no-match '(x) "()")
      (check-no-match '(x) "(1 2)")
      (check-no-match '(x y) "(1 . 2)")
      (check-no-match '(x) "1")
      (check-no-match '() "#()"))

    (define (test-repeated-matches)
      (check-match '(x ...) "()" '((x . ())))
      (check-match '(x ...) "(1 2 3)" '((x . (1 2 3))))
      (check-match '(head middle ... last) "(1 2)" '((head . 1) (middle . ()) (last . 2)))
      (check-match '(head middle ... last) "(1 2 3 4)" '((head . 1) (middle . (2 3)) (last . 4)))
      (check-match '(x ... first last) "(1 2)" '((x . ()) (first . 1) (last . 2)))
      (check-match '(x ... first last) "(1 2 3 4)" '((x . (1 2)) (first . 3) (last . 4)))
      (check-match '(x ... first last . tail) "(1 . (2 . 3))"
                   '((x . ()) (first . 1) (last . 2) (tail . 3)))
      (check-match '((name value) ...) "((a 1) (b 2))" '((name . (a b)) (value . (1 2))))
      (check-match '((name value) ...) "()" '((name . ()) (value . ())))
      (check-match '((x ...) ...) "(() (a b) ())" '((x . (() (a b) ()))))
      (check-match '((x ...) ...) "()" '((x . ())))
      (check-match '(((x ...) ...) ...) "((() (a)) () ((b c)))" '((x . ((() (a)) () ((b c))))))
      (check-match '((name value ...) ...) "((a) (b 1 2))" '((name . (a b)) (value . (() (1 2)))))
      (check-match '(_ ...) "(1 2 3)" '())
      (check-match '(1 ... last) "(1 1 2)" '((last . 2)))
      (check-match '(x ... . tail) "(1 2)" '((x . (1 2)) (tail . ())))
      (check-match '(x ... . tail) "(1 . (2 . 3))" '((x . (1 2)) (tail . 3)))
      (check-match '(x ... . tail) "()" '((x . ()) (tail . ())))
      (check-match '(head x ... . tail) "(1 . 2)" '((head . 1) (x . ()) (tail . 2)))
      (check-match '(head x ... last . tail) "(1 2 3 . 4)"
                   '((head . 1) (x . (2)) (last . 3) (tail . 4)))
      (check-match '(head x ... first last . tail) "(1 . (2 3 . (4 5 . 6)))"
                   '((head . 1) (x . (2 3)) (first . 4) (last . 5) (tail . 6)))
      ;; The constant #f is distinct from an absent repeated item or tail pattern.
      (check-match '(#f ...) "()" '())
      (check-match '(#f ... last . #f) "(#f #f 3 . #f)" '((last . 3)))
      (check-no-match '(#f ... last . #f) "(#f 3)")
      (check-no-match '(head x ... last) "(1)")
      (check-no-match '(x ... first last) "(1)")
      (check-no-match '(x ...) "(1 . 2)")
      (check-no-match '((x y) ...) "((1 2) (3))")
      (check-no-match '(1 ... last) "(1 2 3)")
      (check-no-match '(x ... . _) "42")
      (check-no-match '(x ... . _) "#()")
      ;; A dotted tail cannot take an arbitrary proper suffix after repetition.
      (check-no-match '(x ... . 2) "(1 2)")
      (check-no-match '(1 ... . tail) "(1 2)")
      (expect (capture-values (dispatch-captures '::: '() '(x ::: last) (read-syntax "(1 2 3)")))
              '((x . (1 2)) (last . 3)))
      (expect (capture-values (dispatch-captures '... '(...) '(x ... y) (read-syntax "(1 ... 2)")))
              '((x . 1) (y . 2)))
      (expect (capture-values (dispatch-captures '::: '() '(... x :::) (read-syntax "(1 2 3)")))
              '((... . 1) (x . (2 3)))))

    (define (test-vector-matches)
      (check-match '#() "#()" '())
      (check-match '#(x y) "#(1 2)" '((x . 1) (y . 2)))
      (check-match '#(x ... last) "#(1 2 3)" '((x . (1 2)) (last . 3)))
      (check-match '#(head x ... first last) "#(1 2 3)"
                   '((head . 1) (x . ()) (first . 2) (last . 3)))
      (check-match '#(head #(x ...) ... first last) "#(1 #(2 3) #() 4 5)"
                   '((head . 1) (x . ((2 3) ())) (first . 4) (last . 5)))
      (check-match '#(x ...) "#()" '((x . ())))
      (check-match '#(#f ...) "#()" '())
      (check-match '#(#f ...) "#(#f #f)" '())
      (check-match '(#(x ...) ...) "(#() #(1 2))" '((x . (() (1 2)))))
      (check-no-match '#(x) "(1)")
      (check-no-match '#(head x ... first last) "#(1 2)")
      (check-no-match '#(x y) "#(1 2 3)")
      (check-no-match '#(1 ... last) "#(1 2 3)")
      (check-no-match '#(#f ...) "#(#f #t)")
      (check-no-match '(x) "#(1)")
      (check-no-match '#(x) "#u8(1)")
      (check-no-match #u8(1) "#(1)"))

    (define (test-flattened-captures)
      ;; Keep outer captures in pattern order while grouping multiple variables
      ;; across repeated vectors and retaining nested empty repetition layers.
      (check-match '(head #(tag (x ...) y) ... last . tail)
                   "(0 #(1 () 2) #(3 (4 5) 6) 7 . 8)"
                   '((head . 0) (tag . (1 3)) (x . (() (4 5)))
                     (y . (2 6)) (last . 7) (tail . 8)))
      (check-match '(head #(tag (x ...) y) ... last . tail)
                   "(0 7 . 8)"
                   '((head . 0) (tag . ()) (x . ()) (y . ()) (last . 7) (tail . 8)))
      (check-match '#((name x ... last) ...) "#((a 1) (b 2 3 4))"
                   '((name . (a b)) (x . (() (2 3))) (last . (1 4)))))

    (define (test-capture-identity)
      (let* ((input (read-syntax "#(a b)"))
             (whole (dispatch-captures '... '() 'whole input))
             (captures (dispatch-captures '... '() '#(x ...) input)))
        (expect (vector-syntax? input) #t)
        (expect (list-syntax? input) #f)
        (expect (syntax? input) #t)
        (expect (syntax-identifier? input) #f)
        (expect (eq? (syntax-loc input) (vector-syntax-loc input)) #t)
        (expect (loc-filename (syntax-loc input)) "match.scm")
        (expect (loc-column (syntax-loc input)) 1)
        (expect (eq? (cdr (assq 'whole whole)) input) #t)
        (expect (eq? (car (cdr (assq 'x captures))) (car (vector-syntax-elements input))) #t)
        (expect (eq? (cadr (cdr (assq 'x captures))) (cadr (vector-syntax-elements input))) #t))
      (let* ((input (read-syntax "(a b)"))
             (captures (dispatch-captures '... '() '(x y) input)))
        (expect (map car captures) '(x y))
        (expect (eq? (cdr (assq 'x captures)) (car (list-syntax-elements input))) #t)
        (expect (eq? (cdr (assq 'y captures)) (cadr (list-syntax-elements input))) #t)
        (expect (loc-filename (syntax-loc (cdr (assq 'x captures)))) "match.scm"))
      (let* ((input (read-syntax "(a . b)"))
             (captures (dispatch-captures '... '() '(x . tail) input)))
        (expect (eq? (cdr (assq 'tail captures)) (list-syntax-improper-tail input)) #t))
      (let* ((input (read-syntax "(a . (b c))"))
             (captures (dispatch-captures '... '() '(x . tail) input)))
        (expect (eq? (cdr (assq 'tail captures)) (list-syntax-improper-tail input)) #t))
      (let* ((input (read-syntax "(a b . #(c))"))
             (captures (dispatch-captures '... '() '(head x ... . tail) input)))
        (expect (map car captures) '(head x tail))
        (expect (eq? (car (cdr (assq 'x captures))) (cadr (list-syntax-elements input))) #t)
        (expect (eq? (cdr (assq 'tail captures)) (list-syntax-improper-tail input)) #t))
      (let* ((input (read-syntax "(a b)"))
             (captures (dispatch-captures '... '() '(x ...) input)))
        (expect (map syntax? (cdr (assq 'x captures))) '(#t #t))
        (expect (eq? (car (cdr (assq 'x captures))) (car (list-syntax-elements input))) #t)
        (expect (eq? (cadr (cdr (assq 'x captures))) (cadr (list-syntax-elements input))) #t))
      ;; An empty-list singleton remains a syntax object; zero repetitions are ().
      (let* ((input (read-syntax "()"))
             (singleton (dispatch-captures '... '() 'x input))
             (repeated (dispatch-captures '... '() '(x ...) input)))
        (expect (eq? (cdr (assq 'x singleton)) input) #t)
        (expect (cdr (assq 'x repeated)) '())))

    (define (test-pattern-dispatch)
      (let* ((called '())
             (dispatch
              (syntax-dispatch '... '(define import)
                               (list (cons '(import name) (lambda (_) (error "unmatched callback invoked")))
                                     (cons '(define name value)
                                           (lambda (captures)
                                             (expect (capture-values captures) '((name . x) (value . 1)))
                                             (set! called (cons 'declined called))
                                             #f))
                                     (cons '(define name value)
                                           (lambda (captures)
                                             (expect (capture-values captures) '((name . x) (value . 1)))
                                             (set! called (cons 'accepted called))
                                             'accepted))
                                     (cons '_ (lambda (_) (error "unexpected fallback"))))))
             (result (dispatch (read-syntax "(define x 1)"))))
        (expect result 'accepted)
        (expect (reverse called) '(declined accepted)))
      (let* ((called '())
             (dispatch
              (syntax-dispatch '... '()
                               (list (cons '_ (lambda (_)
                                                (set! called (cons 'first called))
                                                #f))
                                     (cons '(x) (lambda (_)
                                                  (set! called (cons 'second called))
                                                  #f))
                                     (cons '(2) (lambda (_) (error "unmatched callback invoked")))))))
        (expect (dispatch (read-syntax "(1)")) #f)
        (expect (reverse called) '(first second)))
      ;; Scheme's other values are truthy, including the empty capture alist.
      (for-each
       (lambda (value)
         (let ((dispatch (syntax-dispatch '... '()
                                          (list (cons '_ (lambda (_) value))
                                                (cons '_ (lambda (_) (error "unexpected fallback")))))))
           (expect (dispatch (read-syntax "1")) value)))
       (list #t '() 0 ""))
      (let ((dispatch (syntax-dispatch '... '()
                                       (list (cons '(1 x) (lambda (_) 'wrong))
                                             (cons '(x y) capture-values)))))
        (expect (dispatch (read-syntax "(2 3)"))
                '((x . 2) (y . 3))))
      (let ((dispatch (syntax-dispatch '... '()
                                       (list (cons #f (lambda (captures)
                                                        (expect captures '())
                                                        '()))))))
        (expect (dispatch (read-syntax "#f")) '())
        (expect (dispatch (read-syntax "#t")) #f))
      (expect ((syntax-dispatch '... '() '()) (read-syntax "x")) #f)
      (expect (raises? (lambda ()
                         ((syntax-dispatch '... '() (list (cons '_ (lambda (_) (error "callback failed")))
                                                          (cons '_ (lambda (_) #t))))
                          (read-syntax "x")))) #t))

    (define (test-syntax-match)
      (run-test test-pattern-parsing)
      (run-test test-dispatch-arguments)
      (run-test test-dispatch-construction)
      (run-test test-capture-variables)
      (run-test test-atomic-matches)
      (run-test test-list-matches)
      (run-test test-repeated-matches)
      (run-test test-vector-matches)
      (run-test test-flattened-captures)
      (run-test test-capture-identity)
      (run-test test-pattern-dispatch))))
