(import
 (scheme base)
 (snail-scheme common)
 (snail-scheme test-cli)
 (snail-scheme test-reader)
 (snail-scheme test-parser)
 (snail-scheme test-llvmlite)
 (snail-scheme test-llvm)
 (snail-scheme test-syntax)
 (snail-scheme test-pattern))

(test-cli)
(test-reader)
(test-parser)
(test-llvmlite)
(test-llvm)
(test-syntax)
(test-pattern)
(display-error "All tests ok\n")
