(define-library (snail-scheme test-syntax-match)
  (export test-syntax-match)
  (import (scheme base)
          (snail-scheme reader)
          (snail-scheme source)
          (snail-scheme syntax)
          (snail-scheme test-utils))
  (begin
    (define (read-syntax text)
      (car (parse-file (string->reader "match.scm" text))))

    (define (datum stx)
      (if (atom-syntax? stx)
          (atom-syntax-value stx)
          (let ((elements (map datum (list-syntax-elements stx)))
                (tail (list-syntax-improper-tail stx))
                (prefix (list-syntax-prefix stx)))
            (cond ((equal? prefix "#") (list->vector elements))
                  ((equal? prefix "#u8") (apply bytevector elements))
                  (else (append elements (if (null? tail) '() (datum tail))))))))

    (define (capture-value value)
      (if (syntax? value) (datum value) (map capture-value value)))

    (define (match-value result)
      (list (match-result-success? result)
            (map (lambda (group)
                   (list (match-group-name group) (match-group-singleton? group)
                         (capture-value (match-group-data group))))
                 (match-result-groups result))))

    (define (check-match pattern text groups)
      (expect (match-value (match-syntax-pattern-arm '... '() pattern (read-syntax text)))
              (list #t groups)))

    (define (check-no-match pattern text)
      (expect (match-value (match-syntax-pattern-arm '... '() pattern (read-syntax text)))
              '(#f ())))

    (define (raises? thunk)
      (guard (ex ((error-object? ex) #t)) (thunk) #f))

    (define (test-pattern-validation)
      (for-each
       (lambda (pattern) (expect (pattern? pattern) #t))
       (list '_ 'x #t #f 42 #\a "hello" #u8(0 255) '()
             '(x . y) '(head middle ... last . tail) '((x ...) ...)
             '#(x ... last) '(_ _)))
      (for-each
       (lambda (pattern) (expect (pattern? pattern) #f))
       (list '... '(... x) '(x ... ...) '(x ... y ...) '(x x)
             '(x . x) '(x (x ...)) '#(x x) '(x . ...) (lambda () #t)))
      (expect (pattern? '(x :::) '::: '()) #t)
      (expect (pattern? '(... x) '::: '()) #t)
      (expect (pattern? '(lit lit _ _) '... '(lit _)) #t)
      (expect (pattern? '(... ...) '... '(...)) #t)
      (expect (pattern? 'x 1 '()) #f)
      (expect (pattern? 'x '... '(1)) #f)
      (expect (pattern? 'x '... 'not-a-list) #f)
      (expect (raises? (lambda () (match-syntax-pattern-arm '... '() '(x x) (read-syntax "(1 2)")))) #t))

    (define (test-atomic-matches)
      (check-match '_ "(anything . here)" '())
      (check-match 'x "(a . b)" '((x #t (a . b))))
      (check-match #f "#f" '())
      (check-match #t "#t" '())
      (check-match 42 "42" '())
      (check-match #\a "#\\a" '())
      (check-match "hello" "\"hello\"" '())
      (check-no-match #f "#t")
      (check-no-match 42 "43")
      (check-no-match "hello" "hello")
      (expect (match-value (match-syntax-pattern-arm '... '(define) '(define name value)
                                                     (read-syntax "(define answer 42)")))
              '(#t ((name #t answer) (value #t 42))))
      (expect (match-result-success? (match-syntax-pattern-arm '... '(define) '(define name value)
                                                               (read-syntax "(other answer 42)"))) #f)
      (expect (match-result-success? (match-syntax-pattern-arm '... '(_) '_ (read-syntax "x"))) #f)
      (expect (match-value (match-syntax-pattern-arm '... '(_) '_ (read-syntax "_"))) '(#t ())))

    (define (test-list-matches)
      (check-match '() "()" '())
      (check-match '(x y) "(1 2)" '((x #t 1) (y #t 2)))
      (check-match '(x (y z)) "[1 {2 3}]" '((x #t 1) (y #t 2) (z #t 3)))
      (check-match '(x . rest) "(1 2 3)" '((x #t 1) (rest #t (2 3))))
      (check-match '(x . rest) "(1 . 2)" '((x #t 1) (rest #t 2)))
      (check-match '(x . rest) "(1)" '((x #t 1) (rest #t ())))
      (check-match '(x y) "(1 . (2))" '((x #t 1) (y #t 2)))
      (check-match '(x y . rest) "(1 . (2 . 3))" '((x #t 1) (y #t 2) (rest #t 3)))
      (check-match '(x . rest) "(1 . #(2))" '((x #t 1) (rest #t #(2))))
      (check-no-match '(x) "()")
      (check-no-match '(x) "(1 2)")
      (check-no-match '(x y) "(1 . 2)")
      (check-no-match '(x) "1")
      (check-no-match '() "#()"))

    (define (test-repeated-matches)
      (check-match '(x ...) "()" '((x #f ())))
      (check-match '(x ...) "(1 2 3)" '((x #f (1 2 3))))
      (check-match '(head middle ... last) "(1 2)" '((head #t 1) (middle #f ()) (last #t 2)))
      (check-match '(head middle ... last) "(1 2 3 4)" '((head #t 1) (middle #f (2 3)) (last #t 4)))
      (check-match '((name value) ...) "((a 1) (b 2))" '((name #f (a b)) (value #f (1 2))))
      (check-match '((name value) ...) "()" '((name #f ()) (value #f ())))
      (check-match '((x ...) ...) "(() (a b) ())" '((x #f (() (a b) ()))))
      (check-match '((x ...) ...) "()" '((x #f ())))
      (check-match '(((x ...) ...) ...) "((() (a)) () ((b c)))" '((x #f ((() (a)) () ((b c))))))
      (check-match '((name value ...) ...) "((a) (b 1 2))" '((name #f (a b)) (value #f (() (1 2)))))
      (check-match '(_ ...) "(1 2 3)" '())
      (check-match '(1 ... last) "(1 1 2)" '((last #t 2)))
      (check-match '(x ... . tail) "(1 2)" '((x #f (1 2)) (tail #t ())))
      (check-match '(x ... . tail) "(1 . (2 . 3))" '((x #f (1 2)) (tail #t 3)))
      (check-match '(x ... . tail) "()" '((x #f ()) (tail #t ())))
      (check-match '(head x ... . tail) "(1 . 2)" '((head #t 1) (x #f ()) (tail #t 2)))
      (check-match '(head x ... last . tail) "(1 2 3 . 4)"
                   '((head #t 1) (x #f (2)) (last #t 3) (tail #t 4)))
      (check-no-match '(head x ... last) "(1)")
      (check-no-match '(x ...) "(1 . 2)")
      (check-no-match '((x y) ...) "((1 2) (3))")
      (check-no-match '(1 ... last) "(1 2 3)")
      (check-no-match '(x ... . _) "42")
      (check-no-match '(x ... . _) "#()")
      ;; A dotted tail cannot take an arbitrary proper suffix after repetition.
      (check-no-match '(x ... . 2) "(1 2)")
      (expect (match-value (match-syntax-pattern-arm '::: '() '(x ::: last) (read-syntax "(1 2 3)")))
              '(#t ((x #f (1 2)) (last #t 3))))
      (expect (match-value (match-syntax-pattern-arm '... '(...) '(x ... y) (read-syntax "(1 ... 2)")))
              '(#t ((x #t 1) (y #t 2))))
      (expect (match-value (match-syntax-pattern-arm '::: '() '(... x :::) (read-syntax "(1 2 3)")))
              '(#t ((... #t 1) (x #f (2 3))))))

    (define (test-vector-matches)
      (check-match '#() "#()" '())
      (check-match '#(x y) "#(1 2)" '((x #t 1) (y #t 2)))
      (check-match '#(x ... last) "#(1 2 3)" '((x #f (1 2)) (last #t 3)))
      (check-match '#(x ...) "#()" '((x #f ())))
      (check-match '(#(x ...) ...) "(#() #(1 2))" '((x #f (() (1 2)))))
      (check-match #u8(0 255) "#u8(0 #xff)" '())
      (check-match 'x "#u8(1 2)" '((x #t #u8(1 2))))
      (check-no-match '#(x) "(1)")
      (check-no-match '(x) "#(1)")
      (check-no-match '#(x) "#u8(1)")
      (check-no-match #u8(1) "#(1)")
      (check-no-match #u8(1) "#u8(2)"))

    (define (test-capture-identity)
      (let* ((input (read-syntax "(a b)"))
             (result (match-syntax-pattern-arm '... '() '(x y) input))
             (groups (match-result-groups result)))
        (expect (eq? (match-group-data (car groups)) (car (list-syntax-elements input))) #t)
        (expect (eq? (match-group-data (cadr groups)) (cadr (list-syntax-elements input))) #t)
        (expect (loc-filename (syntax-loc (match-group-data (car groups)))) "match.scm"))
      (let* ((input (read-syntax "(a . b)"))
             (groups (match-result-groups (match-syntax-pattern-arm '... '() '(x . tail) input))))
        (expect (eq? (match-group-data (cadr groups)) (list-syntax-improper-tail input)) #t)))

    (define (test-pattern-dispatch)
      (let* ((called '())
             (dispatch
              (syntax-pattern '... '(define import)
                              (list (cons '(import name) (lambda (_) (set! called '(wrong))))
                                    (cons '(define name value)
                                          (lambda (result)
                                            (set! called (match-value result))
                                            #f))
                                    (cons '_ (lambda (_) (error "unexpected fallback"))))))
             (result (dispatch (read-syntax "(define x 1)"))))
        (expect (syntax-pattern-dispatch-result-success? result) #t)
        (expect (syntax-pattern-dispatch-result-returned result) #f)
        (expect called '(#t ((name #t x) (value #t 1)))))
      (let ((dispatch (syntax-pattern '... '()
                                      (list (cons '(1 x) (lambda (_) 'wrong))
                                            (cons '(x y) match-value)))))
        (expect (syntax-pattern-dispatch-result-returned (dispatch (read-syntax "(2 3)")))
                '(#t ((x #t 2) (y #t 3)))))
      (let ((dispatch (syntax-pattern '... '() (list (cons #f (lambda (_) '()))))))
        (expect (syntax-pattern-dispatch-result-success? (dispatch (read-syntax "#f"))) #t)
        (expect (syntax-pattern-dispatch-result-returned (dispatch (read-syntax "#f"))) '())
        (expect (syntax-pattern-dispatch-result-success? (dispatch (read-syntax "#t"))) #f)
        (expect (syntax-pattern-dispatch-result-returned (dispatch (read-syntax "#t"))) '()))
      (expect (syntax-pattern-dispatch-result-success? ((syntax-pattern '... '() '()) (read-syntax "x"))) #f)
      (expect (raises? (lambda () (syntax-pattern '... '() (list (cons '(x x) (lambda (_) #t)))))) #t)
      (expect (raises? (lambda () (syntax-pattern '... '() (list (cons '_ 42))))) #t)
      (expect (raises? (lambda ()
                         ((syntax-pattern '... '() (list (cons '_ (lambda (_) (error "callback failed")))
                                                         (cons '_ (lambda (_) #t))))
                          (read-syntax "x")))) #t))

    (define (test-syntax-match)
      (run-test test-pattern-validation)
      (run-test test-atomic-matches)
      (run-test test-list-matches)
      (run-test test-repeated-matches)
      (run-test test-vector-matches)
      (run-test test-capture-identity)
      (run-test test-pattern-dispatch))))
