(import (scheme base)
        (only (snail-scheme trace) test-trace)
        (only (snail-scheme build) test-build)
        (only (snail-scheme common) display-error)
        (only (snail-scheme reader) test-reader)
        (only (snail-scheme parser) test-parser)
        (only (snail-scheme library) test-library)
        (only (snail-scheme wasm) test-wasm)
        (only (snail-scheme syntax-parser) test-syntax-parser)
        (only (snail-scheme pattern) test-pattern)
        (only (snail-scheme expand) test-expand))

(test-trace)
(test-build)
(test-reader)
(test-parser)
(test-library)
(test-wasm)
(test-syntax-parser)
(test-pattern)
(test-expand)
(display-error "All tests ok\n")
